package com.google.android.gms.games.internal.player;

import android.text.TextUtils;

/* JADX INFO: loaded from: /tmp/tmp.15aGftnP89/classes.dex */
public final class zze {
    public final String name;
    public final String zzcc;
    public final String zzch;
    public final String zzll;
    public final String zzlm;
    public final String zzln;
    public final String zzlo;
    public final String zzlp;
    public final String zzlq;
    public final String zzlr;
    public final String zzls;
    public final String zzlt;
    public final String zzlu;
    public final String zzlv;
    public final String zzlw;
    public final String zzlx;
    public final String zzly;
    public final String zzlz;
    public final String zzma;
    private final String zzmb;
    public final String zzmc;
    public final String zzmd;
    public final String zzme;
    public final String zzmf;
    public final String zzmg;
    public final String zzmh;
    public final String zzmi;
    public final String zzmj;
    public final String zzmk;
    public final String zzml;
    public final String zzmm;
    public final String zzmn;
    public final String zzmo;
    public final String zzmp;
    public final String zzmq;

    public zze(String str) {
        String strConcat;
        if (TextUtils.isEmpty(str)) {
            this.zzll = "external_player_id";
            this.zzlm = "profile_name";
            this.zzln = "profile_icon_image_uri";
            this.zzlo = "profile_icon_image_url";
            this.zzlp = "profile_hi_res_image_uri";
            this.zzlq = "profile_hi_res_image_url";
            this.zzlr = "last_updated";
            this.zzls = "is_in_circles";
            this.zzlt = "played_with_timestamp";
            this.zzlu = "current_xp_total";
            this.zzlv = "current_level";
            this.zzlw = "current_level_min_xp";
            this.zzlx = "current_level_max_xp";
            this.zzly = "next_level";
            this.zzlz = "next_level_max_xp";
            this.zzma = "last_level_up_timestamp";
            this.zzcc = "player_title";
            this.zzmb = "has_all_public_acls";
            this.zzmc = "is_profile_visible";
            this.zzmd = "most_recent_external_game_id";
            this.zzme = "most_recent_game_name";
            this.zzmf = "most_recent_activity_timestamp";
            this.zzmg = "most_recent_game_icon_uri";
            this.zzmh = "most_recent_game_hi_res_uri";
            this.zzmi = "most_recent_game_featured_uri";
            this.zzmj = "has_debug_access";
            this.zzch = "gamer_tag";
            this.name = "real_name";
            this.zzmk = "banner_image_landscape_uri";
            this.zzml = "banner_image_landscape_url";
            this.zzmm = "banner_image_portrait_uri";
            this.zzmn = "banner_image_portrait_url";
            this.zzmo = "gamer_friend_status";
            this.zzmp = "gamer_friend_update_timestamp";
            strConcat = "is_muted";
        } else {
            String strValueOf = String.valueOf(str);
            this.zzll = "external_player_id".length() != 0 ? strValueOf.concat("external_player_id") : new String(strValueOf);
            String strValueOf2 = String.valueOf(str);
            this.zzlm = "profile_name".length() != 0 ? strValueOf2.concat("profile_name") : new String(strValueOf2);
            String strValueOf3 = String.valueOf(str);
            this.zzln = "profile_icon_image_uri".length() != 0 ? strValueOf3.concat("profile_icon_image_uri") : new String(strValueOf3);
            String strValueOf4 = String.valueOf(str);
            this.zzlo = "profile_icon_image_url".length() != 0 ? strValueOf4.concat("profile_icon_image_url") : new String(strValueOf4);
            String strValueOf5 = String.valueOf(str);
            this.zzlp = "profile_hi_res_image_uri".length() != 0 ? strValueOf5.concat("profile_hi_res_image_uri") : new String(strValueOf5);
            String strValueOf6 = String.valueOf(str);
            this.zzlq = "profile_hi_res_image_url".length() != 0 ? strValueOf6.concat("profile_hi_res_image_url") : new String(strValueOf6);
            String strValueOf7 = String.valueOf(str);
            this.zzlr = "last_updated".length() != 0 ? strValueOf7.concat("last_updated") : new String(strValueOf7);
            String strValueOf8 = String.valueOf(str);
            this.zzls = "is_in_circles".length() != 0 ? strValueOf8.concat("is_in_circles") : new String(strValueOf8);
            String strValueOf9 = String.valueOf(str);
            this.zzlt = "played_with_timestamp".length() != 0 ? strValueOf9.concat("played_with_timestamp") : new String(strValueOf9);
            String strValueOf10 = String.valueOf(str);
            this.zzlu = "current_xp_total".length() != 0 ? strValueOf10.concat("current_xp_total") : new String(strValueOf10);
            String strValueOf11 = String.valueOf(str);
            this.zzlv = "current_level".length() != 0 ? strValueOf11.concat("current_level") : new String(strValueOf11);
            String strValueOf12 = String.valueOf(str);
            this.zzlw = "current_level_min_xp".length() != 0 ? strValueOf12.concat("current_level_min_xp") : new String(strValueOf12);
            String strValueOf13 = String.valueOf(str);
            this.zzlx = "current_level_max_xp".length() != 0 ? strValueOf13.concat("current_level_max_xp") : new String(strValueOf13);
            String strValueOf14 = String.valueOf(str);
            this.zzly = "next_level".length() != 0 ? strValueOf14.concat("next_level") : new String(strValueOf14);
            String strValueOf15 = String.valueOf(str);
            this.zzlz = "next_level_max_xp".length() != 0 ? strValueOf15.concat("next_level_max_xp") : new String(strValueOf15);
            String strValueOf16 = String.valueOf(str);
            this.zzma = "last_level_up_timestamp".length() != 0 ? strValueOf16.concat("last_level_up_timestamp") : new String(strValueOf16);
            String strValueOf17 = String.valueOf(str);
            this.zzcc = "player_title".length() != 0 ? strValueOf17.concat("player_title") : new String(strValueOf17);
            String strValueOf18 = String.valueOf(str);
            this.zzmb = "has_all_public_acls".length() != 0 ? strValueOf18.concat("has_all_public_acls") : new String(strValueOf18);
            String strValueOf19 = String.valueOf(str);
            this.zzmc = "is_profile_visible".length() != 0 ? strValueOf19.concat("is_profile_visible") : new String(strValueOf19);
            String strValueOf20 = String.valueOf(str);
            this.zzmd = "most_recent_external_game_id".length() != 0 ? strValueOf20.concat("most_recent_external_game_id") : new String(strValueOf20);
            String strValueOf21 = String.valueOf(str);
            this.zzme = "most_recent_game_name".length() != 0 ? strValueOf21.concat("most_recent_game_name") : new String(strValueOf21);
            String strValueOf22 = String.valueOf(str);
            this.zzmf = "most_recent_activity_timestamp".length() != 0 ? strValueOf22.concat("most_recent_activity_timestamp") : new String(strValueOf22);
            String strValueOf23 = String.valueOf(str);
            this.zzmg = "most_recent_game_icon_uri".length() != 0 ? strValueOf23.concat("most_recent_game_icon_uri") : new String(strValueOf23);
            String strValueOf24 = String.valueOf(str);
            this.zzmh = "most_recent_game_hi_res_uri".length() != 0 ? strValueOf24.concat("most_recent_game_hi_res_uri") : new String(strValueOf24);
            String strValueOf25 = String.valueOf(str);
            this.zzmi = "most_recent_game_featured_uri".length() != 0 ? strValueOf25.concat("most_recent_game_featured_uri") : new String(strValueOf25);
            String strValueOf26 = String.valueOf(str);
            this.zzmj = "has_debug_access".length() != 0 ? strValueOf26.concat("has_debug_access") : new String(strValueOf26);
            String strValueOf27 = String.valueOf(str);
            this.zzch = "gamer_tag".length() != 0 ? strValueOf27.concat("gamer_tag") : new String(strValueOf27);
            String strValueOf28 = String.valueOf(str);
            this.name = "real_name".length() != 0 ? strValueOf28.concat("real_name") : new String(strValueOf28);
            String strValueOf29 = String.valueOf(str);
            this.zzmk = "banner_image_landscape_uri".length() != 0 ? strValueOf29.concat("banner_image_landscape_uri") : new String(strValueOf29);
            String strValueOf30 = String.valueOf(str);
            this.zzml = "banner_image_landscape_url".length() != 0 ? strValueOf30.concat("banner_image_landscape_url") : new String(strValueOf30);
            String strValueOf31 = String.valueOf(str);
            this.zzmm = "banner_image_portrait_uri".length() != 0 ? strValueOf31.concat("banner_image_portrait_uri") : new String(strValueOf31);
            String strValueOf32 = String.valueOf(str);
            this.zzmn = "banner_image_portrait_url".length() != 0 ? strValueOf32.concat("banner_image_portrait_url") : new String(strValueOf32);
            String strValueOf33 = String.valueOf(str);
            this.zzmo = "gamer_friend_status".length() != 0 ? strValueOf33.concat("gamer_friend_status") : new String(strValueOf33);
            String strValueOf34 = String.valueOf(str);
            this.zzmp = "gamer_friend_update_timestamp".length() != 0 ? strValueOf34.concat("gamer_friend_update_timestamp") : new String(strValueOf34);
            String strValueOf35 = String.valueOf(str);
            strConcat = "is_muted".length() != 0 ? strValueOf35.concat("is_muted") : new String(strValueOf35);
        }
        this.zzmq = strConcat;
    }
}
