"""Guild main quest lines (v75 story engine data; deobf/GUILD_EXPANSION_SPEC.md §10).

A story is a list of chapters. A chapter is offered by the guild leader (hub node 720) once the player has the
level, the contracts (rep) and the previous chapter; accepting starts its first step. Each step is a scene at one
NPC (an existing conversation file or a new character added by the story) that plays when the step is current and
its `need` conditions hold; an option with go=None finishes the step (next step, or the chapter end with its
promotion). `jump` names another step of the same chapter.

Beat:  {'t': text | [(cond, text), ..., (None, default)], 'o': [option, ...]}
Option: {'t': text, 'go': beat index | None (finish step) | 'hold' (end, step stays), 'a': actions, 'c': conds,
         'jump': step label}
Text markup: [BLUE]..[] narration.  Choice variables: ekg_c_<g>_<key>.
"""

W_NPCS = [
    # --- chapter 1: Brann in the farmlands, then home at the guild hall
    dict(id='ekg_w_brann_h8', map='H8', at=(2196, 1096), kind='static', name='Brann Holloway', sprite='male_brown_12',
         portrait=18, show=('1.1', '1.3')),
    dict(id='ekg_w_scout1', group='ekg_w_scouts', map='H8', at=(2188, 1384), kind='foe', spawn='guild_mercenary', name='Crimson Scout',
         faction='bandits', show=('1.1', '1.2')),
    dict(id='ekg_w_scout2', group='ekg_w_scouts', map='H8', at=(2387, 1421), kind='foe', spawn='guild_mercenary', name='Crimson Scout',
         faction='bandits', show=('1.1', '1.2')),
    dict(id='ekg_w_scout3', group='ekg_w_scouts', map='H8', at=(2623, 1533), kind='foe', spawn='bandit_male_assasin', name='Crimson Scout Leader',
         faction='bandits', show=('1.1', '1.2')),
    dict(id='ekg_w_brann', map='NG_warriors', at=(448, 602), kind='static', name='Brann Holloway', sprite='male_brown_12',
         portrait=18, show=('1.3', None)),
    # --- chapter 2: Lyse in Freetown, Garrick on the Rhoneis Plains
    dict(id='ekg_w_lyse', map='FT', at=(1351, 783), kind='static', name='Lyse Corwen', sprite='female_red_1', portrait=12,
         gender='f', show=('2.2', '2.4')),
    dict(id='ekg_w_garrick', map='F10', at=(2892, 1024), kind='foe', spawn='outlaw_chief', name='Garrick the Knife',
         faction='bandits', show=('2.3', '2.3')),
    dict(id='ekg_w_cut1', map='F10', at=(2860, 1060), kind='foe', spawn='bandit_male_assasin', name='Crimson Cutthroat',
         faction='bandits', show=('2.3', '2.3')),
    dict(id='ekg_w_cut2', map='F10', at=(2920, 990), kind='foe', spawn='bandit_male_assasin', name='Crimson Cutthroat',
         faction='bandits', show=('2.3', '2.3')),
    dict(id='ekg_w_lyse_ng', map='NG_warriors', at=(425, 635), kind='static', name='Lyse Corwen', sprite='female_red_1',
         portrait=12, gender='f', show=('3.1', None), cond='VariableEqual#ekg_c_warriors_lyse,1'),
    # --- chapter 3: Oreth the Binder in the Trollfens
    dict(id='ekg_w_oreth', map='E8', at=(1624, 421), kind='talker', spawn='I9_necromancer', name='Oreth the Binder',
         show=('3.1', '3.1')),
    # --- chapter 4: Captain Sera Blackwell at Sanctuary Peak
    dict(id='ekg_w_sera', map='D13', at=(1045, 707), kind='talker', spawn='friguld_captain', name='Captain Sera Blackwell',
         show=('4.2', '4.2'), group='ekg_w_sera_band'),
    dict(id='ekg_w_sera_g1', map='D13', at=(1010, 740), kind='talker', spawn='knight_hostile', name='Crimson Sword',
         show=('4.2', '4.2'), group='ekg_w_sera_band', talk=False),
    dict(id='ekg_w_sera_g2', map='D13', at=(1080, 680), kind='talker', spawn='knight_hostile', name='Crimson Sword',
         show=('4.2', '4.2'), group='ekg_w_sera_band', talk=False),
    # --- chapter 5: the courier on the Imperial Coast
    dict(id='ekg_w_maddoc', map='I8', at=(1201, 959), kind='foe', spawn='outlaw_king', name='Maddoc the Courier',
         faction='bandits', show=('5.1', '5.1')),
    dict(id='ekg_w_esc1', map='I8', at=(1170, 990), kind='foe', spawn='rogue_melee_12', name='Crimson Escort',
         faction='bandits', show=('5.1', '5.1')),
    dict(id='ekg_w_esc2', map='I8', at=(1230, 930), kind='foe', spawn='rogue_archer_12', name='Crimson Escort',
         faction='bandits', show=('5.1', '5.1')),
    # --- chapter 6: the beastbinder in the Sunken Citadel
    dict(id='ekg_w_handler', map='H3_cave', at=(316, 1545), kind='foe', spawn='forsaken_mage', name='Crimson Beastbinder',
         faction='enemy', show=('6.2', '6.2')),
    # --- chapter 7: Varrek Dunmore at the Imperial Fortress
    dict(id='ekg_w_varrek', map='J9_castle', at=(870, 1560), kind='talker', spawn='forsaken_knight2', name='Varrek Dunmore',
         show=('7.2', '7.2'), group='ekg_w_company'),
    dict(id='ekg_w_lt1', map='J9_castle', at=(980, 1535), kind='talker', spawn='forsaken_knight', name='Crimson Lieutenant',
         show=('7.2', '7.2'), group='ekg_w_company', talk=False),
    dict(id='ekg_w_lt2', map='J9_castle', at=(763, 1599), kind='talker', spawn='forsaken_knight', name='Crimson Lieutenant',
         show=('7.2', '7.2'), group='ekg_w_company', talk=False),
]

W_ITEMS = [
    (9501, 'Crimson Sash', 'A torn red sash, stiff with dried blood. Sewn inside: the sigil of a clenched gauntlet.', 'letters'),
    (9502, "Vane's Letters", "Sealed letters from Lord Aldric Vane to 'V.D.', promising coin for 'beast-work' along the King's roads.", 'letters'),
]

B = '[BLUE](%s)[]'

WARRIORS = dict(
    npcs=W_NPCS, items=W_ITEMS,
    idle={  # default lines of the new characters when no scene is due
        'ekg_w_brann_h8': "[BLUE](Brann is binding his leg with a strip of cloak)[] I'll live. Go on.",
        'ekg_w_brann': [('VariableEqual#ekg_st_warriors,100', "Guild Master. [BLUE](Brann grins)[] Never thought I'd live to say that to someone I pulled out of a ditch. Well. You pulled me."),
                        ('VariableGreater#ekg_st_warriors,{7.2}', "Varrek... [BLUE](He shakes his head)[] Twenty years I called him brother. Don't mind me."),
                        (None, "[BLUE](Brann Holloway, scout of the Warriors' Guild, is sharpening a short sword)[] The leg aches when it rains. It rains a lot in New Garand.")],
        'ekg_w_lyse': "[BLUE](Lyse watches the door more than her drink)[] Not here. Not now.",
        'ekg_w_lyse_ng': "[BLUE](Lyse is going through the guild's supply ledgers, frowning)[] Your quartermaster couldn't count to ten with both hands. I'm fixing it. You're welcome.",
        'ekg_w_oreth': "Leave me be.",
        'ekg_w_sera': "Keep walking, guildling.",
        'ekg_w_varrek': "...",
    },
    chapters=[
        # ------------------------------------------------------------------ 1
        dict(title='Blood on the Road', level=8, rep=2, promote=True,
             brief="A patrol of ours never came back from the farmlands south of the city. [BLUE]Brann Holloway[] led it; he's been walking those roads for twenty years and he doesn't get lost. Monsters, the farmers say. I want to hear it from Brann, or from what's left of him. [BLUE]The New Garand Farmlands[], recruit. Find them.",
             steps=[
                 dict(label='brann', at='ekg_w_brann_h8',
                      j="Brann Holloway's patrol vanished in the New Garand Farmlands. Sergeant Daukar wants to know what happened.",
                      scene=[
                          dict(t=B % "A grey-bearded man sits against a broken cart, a crossbow bolt snapped off in his thigh" + " Guild colours. Thank the Three. Is Daukar with you? No... just you. Right.",
                               o=[dict(t='What happened here?', go=1),
                                  dict(t="Hold still. Let me see that leg.", go=1, a='GainXP#50')]),
                          dict(t="Monsters, the farmers'll say. There wasn't a beast among them. Men, a dozen, red sashes, crossbows. They knew our route and they knew our numbers. Went for the carts first, then for us. Took the guild seals off the dead. [BLUE](He spits)[] Seals. What does a cutthroat want with guild seals?",
                               o=[dict(t='Are they still around?', go=2),
                                  dict(t='Why take the seals?', go=3)]),
                          dict(t="Three of them stayed behind to pick the bodies clean. I heard them laughing. South and east of here, toward the old fields. I can't walk and you can. Make them stop laughing.",
                               o=[dict(t="I'll deal with them.", go=None),
                                  dict(t='Why take the seals?', go=3)]),
                          dict(t="Put a guild seal on a dead minotaur and nobody asks who killed it. Put one on a burned farm and everyone asks why the guild didn't come. You follow? Somebody wants the Warriors' Guild to look useless. Three of them are still out there, to the south-east. Start with them.",
                               o=[dict(t="I'll deal with them.", go=None)]),
                      ]),
                 dict(label='scouts', at='ekg_w_brann_h8',
                      need=['NPCIsDead#ekg_w_scout1', 'NPCIsDead#ekg_w_scout2', 'NPCIsDead#ekg_w_scout3'],
                      j="Three of the ambushers stayed behind in the farmlands, south-east of Brann. I must kill them and return to him.",
                      scene=[
                          dict(t="I heard it from here. [BLUE](Brann looks at what you carry)[] Their leader wore this? Let me see.",
                               o=[dict(t=B % "Show him the red sash you took from the leader", go=1, a='GainItem#9501')]),
                          dict(t="Stitched inside. A clenched gauntlet. [BLUE](His face goes grey, and not from the wound)[] I know that mark. Take it to Daukar. Tell her Brann said: it's the Company. She'll know. I'll limp home on my own; it's what I'm good at.",
                               o=[dict(t='Can you make it back?', go=2),
                                  dict(t="I'll tell her.", go=None, a='GainXP#300')]),
                          dict(t="I've walked out of worse with fewer legs. Go.",
                               o=[dict(t="I'll tell her.", go=None, a='GainXP#300')]),
                      ]),
                 dict(label='report', at='NG_warriors_daukar', need=['PlayerHasItems#9501,1'],
                      j="Brann recognised the mark on the sash: 'the Company'. I must take it to Sergeant Daukar.",
                      scene=[
                          dict(t="Brann's alive? Good. That old goat owes me money. [BLUE](She takes the sash, and her jaw tightens at the gauntlet)[] The Crimson Company.",
                               o=[dict(t='Who are they?', go=1)]),
                          dict(t="Sellswords. The best-paid in the four kingdoms, and the worst. Their commander is [BLUE]Varrek Dunmore[]. Twenty years ago he was a sergeant of this guild, standing where I stand. He sold his oath to the highest bidder and we struck his name from the wall.",
                               o=[dict(t='Why would he attack guild patrols?', go=2),
                                  dict(t='Brann seemed to know the mark.', go=3)]),
                          dict(t="Because every lord who stops trusting the Guild starts buying the Company. Burn a few farms, leave our seals in the ashes, and the King's council asks why he still pays for us. Varrek always did understand coin better than honour.",
                               o=[dict(t='What do we do?', go=4)]),
                          dict(t="Brann served under Varrek. They were brothers, near enough. Don't ask him about it unless you want your nose broken. [BLUE](Almost gently)[] He's the reason Brann walks the roads alone.",
                               o=[dict(t='What do we do?', go=4)]),
                          dict(t="You did well, and you kept your head. That's a soldier, not a recruit. [BLUE](She hands you a ring)[] Keep your eyes open and your contracts filled. When the Company moves again, I'll need you.",
                               o=[dict(t='I stand ready, Sergeant.', go=None, a='LoseItems#9501,1')]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 2
        dict(title='Red Sashes', level=10, rep=3,
             brief="The Company recruits in Freetown; half the port's taverns are full of their coin. [BLUE]Toel[] runs our guildhouse there and he keeps his ears open. Go to him. Find out who pays the Company, and what for.",
             steps=[
                 dict(label='toel', at='FT_warriors_toel',
                      j="Daukar sent me to Toel, at the Warriors' Guildhouse in Freetown, to learn who pays the Crimson Company.",
                      scene=[
                          dict(t="Daukar's runner told me you'd come. Sit. Freetown is crawling with red sashes this season; the Company pays three silver a day and asks no questions. Most of my own recruits walked across the square and signed with them.",
                               o=[dict(t='Anyone who might talk?', go=1)]),
                          dict(t="One. A woman named [BLUE]Lyse Corwen[]. The Company's quartermaster, if the drunks are right. For a week she's been asking, quietly, what the Guild does with deserters. Evenings she waits on the square by the [BLUE]watch post[], near the Generous King, pretending not to wait for anyone. Be gentle. Frightened people bolt.",
                               o=[dict(t="I'll find her.", go=None)]),
                      ]),
                 dict(label='lyse', at='ekg_w_lyse',
                      j="Toel says a Company quartermaster, Lyse Corwen, wants out. She waits on the square by the watch post in Freetown, near the Generous King.",
                      scene=[
                          dict(t=B % "A thin woman with ink-stained fingers looks up sharply" + " Guild. It's on you like a smell. Sit down before someone notices you standing over me.",
                               o=[dict(t='Toel says you want out of the Company.', go=1),
                                  dict(t='I hear you ask a lot of questions.', go=1)]),
                          dict(t="I kept Varrek's books for six years. Pay, rations, bribes. Then the entries started saying [BLUE]'beast-work'[], paid by a lord's steward, in gold. I asked what it meant. The next morning my ledger was gone and [BLUE]Garrick the Knife[] was sleeping outside my door.",
                               o=[dict(t='Who is Garrick?', go=2)]),
                          dict(t="Varrek's dog. He took my ledger to sell it back to Varrek with my name on it. He's camped on the [BLUE]Rhoneis Plains[], east, with two of his friends, waiting for his pay. Bring me that ledger and I'll tell you everything in it. Every name.",
                               o=[dict(t="Stay here. I'll bring it back.", go=None)]),
                      ]),
                 dict(label='garrick', at='ekg_w_lyse', need=['NPCIsDead#ekg_w_garrick'],
                      j="Garrick the Knife took Lyse's ledger. He's camped on the Rhoneis Plains, far to the east of Freetown's farmland, with two cutthroats.",
                      scene=[
                          dict(t=B % "You set the oilcloth ledger you took from Garrick on the table. Lyse lets out a long breath" + " He's dead? Good. Look here. And here.",
                               o=[dict(t='Tell me what it says.', go=1)]),
                          dict(t="Forty payments in two years from [BLUE]Lord Aldric Vane[]'s steward. Vane sits on the King's council. And these: 'O. the Binder, Trollfens, for beasts delivered.' Varrek isn't hiring swords to fight monsters. He is buying the monsters. Somebody named Oreth drives them onto the roads, the Company 'saves' the villages, and Vane tells the King the Guild is finished.",
                               o=[dict(t="That's everything I need.", go=2)]),
                          dict(t="Then here is what I need. Varrek will know by tomorrow that Garrick is dead. What happens to me now?",
                               o=[dict(t="Come to New Garand. The Guild protects those who help it.", go=3, a='SetVariable#ekg_c_warriors_lyse,1'),
                                  dict(t=B % "Give her 200 gold" + " Take this and disappear. Somewhere far.", go=4, a='SetVariable#ekg_c_warriors_lyse,2;LoseGold#200', c='PlayerHasGold#200'),
                                  dict(t="You kept Varrek's books while he murdered our people. The Freetown watch can have you.", go=5, a='SetVariable#ekg_c_warriors_lyse,3;GainGold#300')]),
                          dict(t="[BLUE](She looks at you for a long moment)[] ...All right. New Garand. If your Sergeant hangs me, I'm haunting you.",
                               o=[dict(t='Tell Toel I sent you. He will get you there safely.', go=None)]),
                          dict(t="[BLUE](She closes her hand over the coins)[] You're a strange sort of soldier. Thank you. If you ever need a ledger read, I'll be... somewhere.",
                               o=[dict(t='Go.', go=None)]),
                          dict(t="[BLUE](She stares at you, then laughs, hollow)[] Of course. You're all the same, guild or company. [BLUE](The watch takes her; the captain presses a bounty into your hand)[]",
                               o=[dict(t='...', go=None)]),
                      ]),
                 dict(label='report', at='FT_warriors_toel',
                      j="Lyse's ledger names Lord Aldric Vane of the King's council as the Company's paymaster, and 'Oreth the Binder' in the Trollfens. I must report to Toel.",
                      scene=[
                          dict(t=[('VariableEqual#ekg_c_warriors_lyse,1', "Lyse Corwen is on a cart to New Garand with two of my best. You did right by her. The Guild keeps its word or it is nothing."),
                                  ('VariableEqual#ekg_c_warriors_lyse,3', "The watch hanged nobody yet, but they will. [BLUE](Toel looks away)[] She came to us. Remember that, the next time someone does."),
                                  (None, "Gone, eh? Best for her, maybe. Varrek doesn't forgive.")],
                               o=[dict(t='Vane pays the Company. And someone called Oreth drives the beasts.', go=1)]),
                          dict(t="A council lord. Beasts on a leash. [BLUE](He is quiet for a while)[] Daukar needs to hear this from you, not from a letter. And go carefully. If Vane has the King's ear, then from here on we are the ones on trial.",
                               o=[dict(t="I'll go to Daukar.", go=None, a='GainXP#600')]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 3
        dict(title='The Beast-Binder', level=12, rep=4, promote=True,
             brief="Oreth the Binder. A hedge-mage with a knack for chaining beasts to his will, and the Company's leash on every troll in the fens. He hides in [BLUE]the Trollfens[], west of here. Find him. What you do with him depends on what he tells you, but the trolls stop raiding either way.",
             steps=[
                 dict(label='oreth', at='ekg_w_oreth',
                      j="Oreth the Binder, the hedge-mage who drives beasts for the Crimson Company, hides in the Trollfens.",
                      scene=[
                          dict(t=B % "A gaunt man in a filthy robe stands among bones, a carved totem hanging from his neck" + " A guild blade. How quaint. Did Varrek finally stop paying you people too?",
                               o=[dict(t='You set monsters on innocent villages.', go=1),
                                  dict(t='Tell me about the Company, and you might live.', go=2)]),
                          dict(t="I set nothing. I ask, politely, in a language the trolls understand. What they do on the road is their nature. What the Company does after is theirs. I am just a craftsman.",
                               o=[dict(t='Tell me about the Company, and you might live.', go=2),
                                  dict(t="A craftsman who's about to die.", go=None, a='NPCHostile#ekg_w_oreth_t;SetVariable#ekg_c_warriors_oreth,2')]),
                          dict(t="[BLUE](He fingers the totem)[] Live? Very well. The real leash isn't mine. It is [BLUE]King Gurguth[], the troll king in his cave in these fens. Varrek gave me a binding stone for him. While Gurguth serves, every troll in the fens serves. Kill the king and the leash snaps.",
                               o=[dict(t='Leave the fens. If I see you again, you die.', go=None, a='NPCDespawn#ekg_w_oreth_t;SetVariable#ekg_c_warriors_oreth,1;GainXP#400'),
                                  dict(t="Thank you. Now you die.", go=None, a='NPCHostile#ekg_w_oreth_t;SetVariable#ekg_c_warriors_oreth,2')]),
                      ]),
                 dict(label='gurguth', at='NG_warriors_daukar', need=['NPCIsDead#king_gurguth'],
                      j="The binding that holds the trolls runs through King Gurguth, in Gurguth Cave in the Trollfens. I must kill him, then report to Daukar.",
                      scene=[
                          dict(t=[('VariableEqual#ekg_c_warriors_oreth,1', "You let the Binder go? [BLUE](She considers)[] Mercy is a soldier's right, when it costs nothing. Pray it cost nothing. And Gurguth?"),
                                  (None, "The Binder's dead and the fens are quiet. And Gurguth?")],
                               o=[dict(t='The troll king is dead. The leash is broken.', go=1)]),
                          dict(t="Then Varrek has lost his beasts, and Vane has lost his excuse. [BLUE](She stands straighter)[] You have faced a troll king and walked back. That makes you a Veteran of the Warriors' Guild. Brann will want to buy you a drink; let him, he never does.",
                               o=[dict(t='Thank you, Sergeant.', go=None)]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 4
        dict(title="The Giants' Price", level=14, rep=6,
             brief="A rider came from Nivarian. [BLUE]Morg[], the warmaster of our hall there, asks for you by name, which means word of you has travelled. He wouldn't say more in a letter. Go to him in [BLUE]Nivarian[].",
             steps=[
                 dict(label='morg', at='NI_warriors_morg',
                      j="Warmaster Morg of the Nivarian hall asked for me by name.",
                      scene=[
                          dict(t="So you're Daukar's troll-killer. [BLUE](Morg looks you over like a horse he's thinking of buying)[] You'll do. Listen. The Company has sent gold up [BLUE]Sanctuary Peak[]. The hill giants up there have a new chief, and he has started wearing a red sash.",
                               o=[dict(t='The Company is buying giants now?', go=1)]),
                          dict(t="Beasts were cheap. Giants are expensive, and a giant with a warband doesn't need a Binder. The one carrying the gold is [BLUE]Captain Sera Blackwell[]. She was a Mercian officer before the Company; a real soldier. Stop the deal.",
                               o=[dict(t="I'll go to Sanctuary Peak.", go=None)]),
                      ]),
                 dict(label='sera', at='ekg_w_sera',
                      j="Captain Sera Blackwell is buying the hill giants of Sanctuary Peak for the Crimson Company.",
                      scene=[
                          dict(t=B % "A woman in dented Mercian plate turns from the cliff's edge, two swords at her back" + " The guild's troll-killer. Varrek said you'd come. He also said you'd be taller.",
                               o=[dict(t="The deal is off. Go home, Captain.", go=1),
                                  dict(t="You're a real soldier, Morg says. Why serve Varrek?", go=2)]),
                          dict(t="Home? The Company is my home. The Guild pays in speeches; Varrek pays in gold, and he pays on time. [BLUE](She draws)[] I don't want this. But I'll finish it.",
                               o=[dict(t="Then let's finish it.", go=None, a='NPCHostile#ekg_w_sera_band;SetVariable#ekg_c_warriors_sera,1'),
                                  dict(t="You're a real soldier, Morg says. Why serve Varrek?", go=2)]),
                          dict(t="[BLUE](She hesitates)[] Because the King forgot us after the war. Because the Guild wanted oaths and gave soup. Varrek remembered our names.",
                               o=[dict(t="Varrek is buying monsters to burn villages. Is that the soldier you are?", go=3),
                                  dict(t="Enough talk.", go=None, a='NPCHostile#ekg_w_sera_band;SetVariable#ekg_c_warriors_sera,1')]),
                          dict(t="...Monsters. [BLUE](A long silence; the wind howls over the peak)[] I thought the beast-work was rumour. [BLUE](She sheathes her swords)[] The giants keep the gold; I won't take it back. But the Company will not get them from me. And when you see Varrek, you tell him Sera Blackwell is done.",
                               o=[dict(t='Go well, Captain.', go=None, a='NPCDespawn#ekg_w_sera_band;SetVariable#ekg_c_warriors_sera,2;GainXP#800')]),
                      ]),
                 dict(label='giant', at='NI_warriors_morg', need=['NPCIsDead#D13_giant'],
                      j="With Blackwell dealt with, the giants' new chief still holds Company gold. I must kill the giant chief on Sanctuary Peak and report to Morg in Nivarian.",
                      scene=[
                          dict(t=[('VariableEqual#ekg_c_warriors_sera,2', "Blackwell walked away? [BLUE](Morg laughs, surprised)[] Then you did something I couldn't: you made a Company captain remember what she was. And the chief?"),
                                  (None, "Blackwell's dead. A waste of a good soldier, but she chose her colours. And the chief?")],
                               o=[dict(t='Dead. The Company gets no giants.', go=1)]),
                          dict(t="Good. [BLUE](He presses a heavy purse into your hand)[] From the Nivarian hall. Tell Daukar the warmasters are watching you now; that is both a compliment and a warning.",
                               o=[dict(t="I'll tell her.", go=None, a='GainGold#1500;GainXP#1500')]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 5
        dict(title='Crown and Coin', level=16, rep=7, promote=True,
             brief="Vane has moved. He stood up in the King's council and asked for the Guild's charter to be given to the Company, citing 'the Guild's failures on the roads'. We need proof of what he's done, and we need it before the next council. His letters to Varrek travel by Company courier along [BLUE]the Imperial Coast[]. Take them.",
             steps=[
                 dict(label='courier', at='NG_warriors_daukar', need=['NPCIsDead#ekg_w_maddoc'],
                      j="Lord Vane's letters to Varrek travel by Company courier, Maddoc, along the Imperial Coast. I must take them and bring them to Daukar.",
                      scene=[
                          dict(t=B % "You empty Maddoc's satchel on Daukar's table: a bundle of letters sealed with Vane's crest" + " [BLUE](She reads in silence, then reads again)[] 'Beast-work'. 'The Guild's charter'. 'Your share of the road tolls'. He signed them. The fool signed them.",
                               o=[dict(t='What do we do with them?', go=1, a='GainItem#9502')]),
                          dict(t="That's your decision, not mine. You carried them. We can take them to the Royal Magistrate: Vane falls in public, the council sees the Company for what it is, and every lord who took Vane's coin becomes our enemy. Or we keep them. Quietly. Vane withdraws his petition, the Guild keeps its charter, and he owes us for the rest of his life.",
                               o=[dict(t="The Magistrate. Let everyone see.", go=2, a='SetVariable#ekg_c_warriors_vane,1;LoseItems#9502,1'),
                                  dict(t="We keep them. A leash for a lord.", go=3, a='SetVariable#ekg_c_warriors_vane,2')]),
                          dict(t="Then it's done openly, the way the founders would have wanted. [BLUE](She seals the letters with the guild's seal)[] It'll cost us friends. But Varrek loses his lord, and a Company without a paymaster is just a mob. You have the heart of a Champion. From today you have the rank as well.",
                               o=[dict(t="I'll wear it well.", go=None)]),
                          dict(t="[BLUE](She smiles thinly)[] Varrek would have done the same. Maybe that's why it's the right choice, and maybe that's why I hate it. Keep them somewhere safe. Vane will try to buy them back, and when he can't, he'll try to kill you. You are a Champion of the Warriors' Guild now. Act like one.",
                               o=[dict(t="I'll wear it well.", go=None)]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 6
        dict(title='Horns of the Underking', level=18, rep=10, promote=True,
             brief="Varrek has answered. The minotaurs of the Ashen Wastes marched on our Nivarian outposts last week, with red-sashed men behind them. He found another Binder, or bought one. [BLUE]Morg[] is gathering a warband in Nivarian. Go and lead it.",
             steps=[
                 dict(label='morg', at='NI_warriors_morg',
                      j="Varrek has turned the minotaurs of the Ashen Wastes on our Nivarian outposts. Morg is gathering a warband in Nivarian.",
                      scene=[
                          dict(t="Three outposts burned. Nine of ours dead. [BLUE](Morg's voice is flat)[] The herd comes from the [BLUE]Sunken Citadel[], and the [BLUE]Underking[] leads it, with one of Varrek's beastbinders at his side, whispering in his ear.",
                               o=[dict(t='Is it Oreth? I let him go.', go=1, c='VariableEqual#ekg_c_warriors_oreth,1'),
                                  dict(t="What's the plan?", go=2)]),
                          dict(t="No. Oreth was seen begging in Freetown, drunk and half blind; the Company took his stone. This one is new, and worse. Mercy is still a soldier's right, but Varrek always has another knife.",
                               o=[dict(t="What's the plan?", go=2)]),
                          dict(t="My warband holds the passes. You go in: kill the binder first, then the Underking. Without the binder the herd scatters; without the Underking it never gathers again. Then come back to me.",
                               o=[dict(t="Consider it done.", go=None)]),
                      ]),
                 dict(label='citadel', at='NI_warriors_morg', need=['NPCIsDead#ekg_w_handler', 'NPCIsDead#mino_underking'],
                      j="I must kill the Crimson Beastbinder and the Minotaur Underking in the Sunken Citadel, in the Ashen Wastes, then report to Morg.",
                      scene=[
                          dict(t="The herd broke and ran into the wastes, and my people held the passes. Not one more outpost burned. [BLUE](Morg grips your forearm, warrior to warrior)[] The warmasters have spoken. You are one of us now.",
                               o=[dict(t="It's an honour, Warmaster.", go=None)]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 7
        dict(title='The Crimson Company', level=20, rep=12,
             brief="It ends now. Varrek has pulled what's left of the Company into [BLUE]the Imperial Fortress[] on the Steel Coast, and he has sent me a challenge in his own hand: the Guild's best, alone, at the gate. Before you go, talk to [BLUE]Brann[]. He has something to say, and he's been working up to it for a week.",
             steps=[
                 dict(label='brann', at='ekg_w_brann',
                      j="Varrek Dunmore has challenged the Guild's best to meet him at the Imperial Fortress. Daukar asked me to speak with Brann first.",
                      scene=[
                          dict(t="So she told you. [BLUE](Brann sets down the whetstone)[] I served under Varrek for eleven years. He taught me to read a road, and to pull an arrow, and to stand in a line when every part of you wants to run.",
                               o=[dict(t='What happened to him?', go=1)]),
                          dict(t="The war. The King cut our pay to half and the Guild told us honour would feed our families. Varrek's wife died that winter. He came back from the funeral, took off his oath-ring, and put it on Daukar's table. I stayed. I've wondered every day since which of us was the fool.",
                               o=[dict(t="He's burned villages since. He isn't that man anymore.", go=2),
                                  dict(t='What do you want me to do?', go=2)]),
                          dict(t="I know. I know. [BLUE](He looks at his hands)[] Just... if there's a way to end it without a grave, look for it. And if there isn't, make it quick. He'd do the same for me.",
                               o=[dict(t="I'll look for a way.", go=None)]),
                      ]),
                 dict(label='varrek', at='ekg_w_varrek',
                      j="Varrek Dunmore waits for me inside the Imperial Fortress, on the Steel Coast.",
                      scene=[
                          dict(t=[('VariableEqual#ekg_c_warriors_sera,2', B % "A tall man in black plate waits in the ruined hall, a greatsword across his knees. Two lieutenants flank him; there is an empty place where a third should stand" + " Sera sends her regards, I suppose. Blackwell always did have a conscience. So you're the one the Guild sends."),
                                  (None, B % "A tall man in black plate waits in the ruined hall, a greatsword across his knees, two lieutenants at his side" + " So you're the one the Guild sends.")],
                               o=[dict(t='Varrek Dunmore. It ends today.', go=1),
                                  dict(t='Brann asked me to find another way.', go=2)]),
                          dict(t="Everything ends. The Guild ended the day it told starving men to eat their oaths. I just stopped pretending. The beasts, the farms... [BLUE](He shrugs, but his eyes do not move from you)[] You don't win a war with clean hands. The King taught me that. So did your Sergeant.",
                               o=[dict(t='Brann asked me to find another way.', go=2),
                                  dict(t='Enough. Draw your sword.', go=None, a='NPCHostile#ekg_w_company;SetVariable#ekg_c_warriors_varrek,1')]),
                          dict(t="[BLUE](For the first time, something cracks in his face)[] Brann. Still alive, the old goat. [BLUE](A long breath)[] What other way? A cell in New Garand while Vane's friends sharpen the axe?",
                               o=[dict(t="Vane has fallen. The Magistrate has his letters. Testify against him and you'll hang no one but the guilty.", go=3, c='VariableEqual#ekg_c_warriors_vane,1'),
                                  dict(t="I hold Vane's letters. Surrender, and the Guild will see you judged fairly.", go=4, c='VariableEqual#ekg_c_warriors_vane,2'),
                                  dict(t="There's no other way. Draw your sword.", go=None, a='NPCHostile#ekg_w_company;SetVariable#ekg_c_warriors_varrek,1')]),
                          dict(t="[BLUE](Varrek laughs, and it turns into something else)[] Vane, in chains. Then the Company is paying for a war it already lost. [BLUE](He lays the greatsword on the floor)[] Tell Brann... tell him I'll see him at the trial. [BLUE](His lieutenants lower their weapons and follow him out)[]",
                               o=[dict(t="Brann will be there.", go=None, a='NPCDespawn#ekg_w_company;SetVariable#ekg_c_warriors_varrek,2;GainXP#2500')]),
                          dict(t="Fairly. [BLUE](A cold smile)[] You hold a council lord by the throat and you want to talk to me about fair. No. You're more like me than Brann ever was. [BLUE](He stands, and the lieutenants draw)[] So let's settle this the old way.",
                               o=[dict(t='So be it.', go=None, a='NPCHostile#ekg_w_company;SetVariable#ekg_c_warriors_varrek,1')]),
                      ]),
                 dict(label='report', at='NG_warriors_daukar',
                      need=[],
                      alt_need=[['VariableEqual#ekg_c_warriors_varrek,2'], ['NPCIsDead#ekg_w_varrek']],
                      j="The confrontation at the Imperial Fortress is over. I must report to Daukar.",
                      scene=[
                          dict(t=[('VariableEqual#ekg_c_warriors_varrek,2', "He surrendered? To you? [BLUE](Daukar sits down, slowly)[] Twenty years I waited to see that man in chains, and now I don't know what I feel. Brann went to the gaol an hour ago. He's still there."),
                                  (None, "It's over, then. [BLUE](She is quiet for a long time)[] He was the best sergeant this guild ever had, once. Brann won't talk about it. Give him time.")],
                               o=[dict(t='The Crimson Company is finished.', go=1)]),
                          dict(t="And the Guild is still standing. Because of you. [BLUE](She looks at the founders' wall, at the scratched-out name that was Varrek's)[] There is one thing left. Come back when you're ready for it. It's the last thing I will ever ask of you.",
                               o=[dict(t="I'll be ready.", go=None, a='GainXP#3000;GainGold#3000')]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 8
        dict(title="The Founders' Oath", level=21, rep=14, promote=True, master=True,
             brief="I'm old, and the Guild needs someone to lead it who can still swing a sword. The founders wrote a law, before the kingdoms had names: whoever slays an elder dragon may claim the seat. Nobody has managed it in a hundred years. First you'll need the blessing of the other halls: [BLUE]Toel[] in Freetown and [BLUE]Morg[] in Nivarian. Then [BLUE]Basrudaxul[], in the Bappasalar Cave. Understand this: a Guild Master serves one guild alone. Every other oath you have sworn will be released.",
             steps=[
                 dict(label='toel', at='FT_warriors_toel',
                      j="To claim the Guild Master's seat I need the blessing of Toel in Freetown and of Morg in Nivarian, then I must slay the elder dragon Basrudaxul.",
                      scene=[
                          dict(t="So Daukar is finally stepping down, and she's chosen you. [BLUE](Toel smiles)[] Freetown's hall gives its blessing. And Freetown's hall wants to be there when you do it; bring me a tooth.",
                               o=[dict(t="A tooth. I'll see what I can do.", go=None, a='GainXP#1000')]),
                      ]),
                 dict(label='morg', at='NI_warriors_morg',
                      j="Toel has given Freetown's blessing. Next, Morg in Nivarian.",
                      scene=[
                          dict(t="[BLUE](Morg does not smile, but he bows, which is rarer)[] Nivarian gives its blessing. The founders' law is a hard law. Most who tried it are still in that cave. Don't join them.",
                               o=[dict(t="I don't intend to.", go=None, a='GainXP#1000')]),
                      ]),
                 dict(label='dragon', at='NG_warriors_daukar', need=['NPCIsDead#H4_dragon_elder'],
                      j="Both halls have given their blessing. I must slay Basrudaxul, the elder red dragon of the Bappasalar Cave in the Southern Dragon Mountains, and return to Daukar.",
                      scene=[
                          dict(t=B % "The whole hall is gathered. Toel came from Freetown, Morg from Nivarian. Brann stands at the front, leaning on a cane and grinning" + " Basrudaxul is dead. [BLUE](Daukar's voice carries to the rafters)[] By the founders' law, spoken before the kingdoms had names...",
                               o=[dict(t=B % "Kneel", go=1)]),
                          dict(t=[('VariableEqual#ekg_c_warriors_lyse,1', "...I stand aside. [BLUE](Somewhere behind you, Lyse Corwen is writing it all down in a ledger, and pretending not to cry)[] Rise, Guild Master of the Warriors' Guild."),
                                  (None, "...I stand aside. Rise, Guild Master of the Warriors' Guild.")],
                               o=[dict(t=B % "Rise", go=2)]),
                          dict(t="The seat is yours, and the charter, and every recruit's fool question at dawn. [BLUE](Daukar grins)[] I'm going to sleep for a month. Brann says he's staying on as your second, and I pity you both.",
                               o=[dict(t="Thank you, Daukar. For everything.", go=None)]),
                      ]),
             ]),
    ])



# ================================================================================================ Seventh House
S_NPCS = [
    # --- chapter 1: Pell hides in the orchid fields east of Kingsbridge; Golden Hand blades hunt him
    dict(id='ekg_s_pell_g9', map='G9', at=(1760, 1376), kind='static', name='Pell', sprite='male_green_1', portrait=28,
         show=('1.1', '1.2')),
    dict(id='ekg_s_blade1', group='ekg_s_blades', map='G9', at=(1824, 1184), kind='foe', spawn='guild_mercenary',
         name='Gilded Blade', faction='bandits', show=('1.1', '1.2')),
    dict(id='ekg_s_blade2', group='ekg_s_blades', map='G9', at=(2016, 1504), kind='foe', spawn='guild_mercenary',
         name='Gilded Blade', faction='bandits', show=('1.1', '1.2')),
    dict(id='ekg_s_blade3', group='ekg_s_blades', map='G9', at=(1760, 1696), kind='foe', spawn='bandit_male_assasin',
         name='Gilded Blade Captain', faction='bandits', show=('1.1', '1.2')),
    # Pell at home in the sewers (not while he is held captive in chapter 6)
    dict(id='ekg_s_pell', map='NG_sewers', at=(352, 928), kind='static', name='Pell', sprite='male_green_1', portrait=28,
         show=('1.3', '5.done')),
    dict(id='ekg_s_pell2', map='NG_sewers', at=(352, 928), kind='static', name='Pell', sprite='male_green_1', portrait=28,
         show=('6.3', None)),
    # --- chapter 2: Anselm Tully, clerk of the Golden Hand, in the Grey Library
    dict(id='ekg_s_anselm', map='FT_library', at=(800, 352), kind='talker', spawn='H6_clerk', name='Anselm Tully',
         portrait=90, show=('2.2', '2.2')),
    # --- chapter 3: Silas Wren, the House's fence
    dict(id='ekg_s_wren', map='NG_sewers', at=(480, 992), kind='talker', spawn='zenmo', name='Silas Wren', portrait=36,
         show=('3.1', '3.1')),
    dict(id='ekg_s_wren_ng', map='NG_sewers', at=(480, 992), kind='static', name='Silas Wren', sprite='male_grey_2',
         portrait=36, show=('3.2', None), cond='VariableEqual#ekg_c_seventh_wren,1'),
    # --- chapter 4: Captain Odran Brand, thief-taker, at the Iron Valley signpost south of Freetown
    dict(id='ekg_s_brand', map='D9', at=(1632, 1248), kind='talker', spawn='hostile_decurion', name='Captain Odran Brand',
         portrait=84, show=('4.2', '4.2'), group='ekg_s_brand_band'),
    dict(id='ekg_s_brand_c1', map='D9', at=(1760, 1312), kind='talker', spawn='mercian_legionnaire_male', name="Brand's Thief-Taker",
         show=('4.2', '4.2'), group='ekg_s_brand_band', talk=False),
    dict(id='ekg_s_brand_c2', map='D9', at=(1760, 1184), kind='talker', spawn='mercian_legionnaire_female', name="Brand's Thief-Taker",
         show=('4.2', '4.2'), group='ekg_s_brand_band', talk=False),
    # --- chapter 5: Maribel Oste, dismissed clerk of the Golden Cove Bank, outside the bank in Friguld
    dict(id='ekg_s_maribel', map='H6', at=(608, 2144), kind='static', name='Maribel Oste', sprite='female_blue_3',
         portrait=19, gender='f', show=('5.1', '5.2')),
    # --- chapter 6: Pell held in the abandoned smuggler hideout, Northern Inori Desert
    dict(id='ekg_s_pell_cap', map='G8_hideout', at=(1248, 1184), kind='static', name='Pell', sprite='male_green_1',
         portrait=28, show=('6.1', '6.2')),
    dict(id='ekg_s_sable', map='G8_hideout', at=(1120, 1056), kind='foe', spawn='forsaken_assassin', name='Sable',
         faction='bandits', show=('6.1', '6.2')),
    dict(id='ekg_s_knife1', map='G8_hideout', at=(1312, 992), kind='foe', spawn='male_nightblade', name='Gilded Knife',
         faction='bandits', show=('6.1', '6.2')),
    dict(id='ekg_s_knife2', map='G8_hideout', at=(960, 1056), kind='foe', spawn='female_nightblade', name='Gilded Knife',
         faction='bandits', show=('6.1', '6.2')),
    # --- chapter 7: Magister Corvin Hale in the Grey Library
    dict(id='ekg_s_hale', map='FT_library', at=(672, 352), kind='talker', spawn='red_wizard', name='Magister Corvin Hale',
         portrait=26, show=('7.2', '7.2'), group='ekg_s_hale_band'),
    dict(id='ekg_s_hale_g1', map='FT_library', at=(544, 352), kind='talker', spawn='forsaken_assassin', name='Golden Hand Enforcer',
         show=('7.2', '7.2'), group='ekg_s_hale_band', talk=False),
    dict(id='ekg_s_hale_g2', map='FT_library', at=(800, 352), kind='talker', spawn='forsaken_knight', name='Golden Hand Enforcer',
         show=('7.2', '7.2'), group='ekg_s_hale_band', talk=False),
]

S_ITEMS = [
    (9511, 'Gilded Token', 'A heavy coin stamped with an open golden hand. Paid to men who ask no questions, by men who own the answers.', 'coin'),
    (9512, "Hale's Letters", "Copies of Magister Corvin Hale's letters: payments to 'W.' for House passwords, and to a Legion clerk for a thief-taker's writ.", 'letters'),
]

SEVENTH = dict(
    npcs=S_NPCS, items=S_ITEMS,
    idle={
        'ekg_s_pell_g9': "[BLUE](Pell is flat in the orchids, barely breathing)[] Are they gone? Tell me they're gone.",
        'ekg_s_pell': [('VariableEqual#ekg_st_seventh,100', "Master. [BLUE](Pell bows, badly, and grins)[] I'm practising. Kardagis says my bow looks like a man falling down stairs."),
                       (None, "[BLUE](Pell is practising a coin trick, dropping the coin every third try)[] Don't tell Torja. She says I have fingers like sausages.")],
        'ekg_s_pell2': [('VariableEqual#ekg_st_seventh,100', "Master. [BLUE](Pell bows, badly, and grins)[] I'm practising. Kardagis says my bow looks like a man falling down stairs."),
                        (None, "[BLUE](Pell has a new scar on his wrist and a new knife on his belt)[] I sleep with my back to the wall now. Torja says that's growing up.")],
        'ekg_s_pell_cap': "[BLUE](Pell is tied to a post, gagged)[] Mmmph!",
        'ekg_s_anselm': "[BLUE](The clerk does not look up from his ledger)[] Appointments are made through the front desk.",
        'ekg_s_wren': "Buying or selling? No? Then you're blocking my light.",
        'ekg_s_wren_ng': "[BLUE](Wren counts coins without looking at them)[] Hale got another letter from me yesterday. Full of lies. I sleep better than I have in years.",
        'ekg_s_brand': "Move along, citizen.",
        'ekg_s_maribel': "[BLUE](Maribel watches the bank's doors like a cat watches a mousehole)[] Not yet. Not here.",
        'ekg_s_hale': "...",
    },
    chapters=[
        # ------------------------------------------------------------------ 1
        dict(title='Loose Lips', level=8, rep=2, promote=True,
             brief="Three drops in a month, and three times the Legion was waiting. Somebody is talking, Associate. [BLUE]Torja[] keeps the tally of every job in this sewer, and she knows who ran them. Start with her. Quietly.",
             steps=[
                 dict(label='torja', at='NG_sewers_torja',
                      j="Three Seventh House drops were raided by the Legion in a month. Kardagis told me to ask Torja who ran them.",
                      scene=[
                          dict(t=B % "Torja turns a greasy ledger toward you and taps three lines" + " The docks, the mill, the Old Bridge. Six of ours in chains, one dead. Kardagis sent you? Then you're what she's got. Gods help us.",
                               o=[dict(t='Who ran the drops?', go=1),
                                  dict(t='Could it be bad luck?', go=2)]),
                          dict(t="A runner called [BLUE]Pell[]. Sixteen, fast, stupid. He ran the Old Bridge drop and he's the only one who got away. Now he won't come home. Word is he's hiding in the red orchid fields [BLUE]east of Kingsbridge[] and that men in fine cloaks are looking for him.",
                               o=[dict(t="Then I'd better find him before they do.", go=None)]),
                          dict(t="[BLUE](She laughs, like a saw on bone)[] Luck? Luck is what the Legion calls it when someone sells them the password. Find the runner, [BLUE]Pell[], in the orchid fields [BLUE]east of Kingsbridge[]. Men in fine cloaks are looking for him too.",
                               o=[dict(t="Then I'd better find him before they do.", go=None)]),
                      ]),
                 dict(label='pell', at='ekg_s_pell_g9',
                      need=['NPCIsDead#ekg_s_blade1', 'NPCIsDead#ekg_s_blade2', 'NPCIsDead#ekg_s_blade3'],
                      j="Pell, the runner who escaped the Old Bridge raid, hides in the red orchid fields east of Kingsbridge. Three hired blades are hunting him; I must deal with them and speak to Pell.",
                      scene=[
                          dict(t=B % "A skinny youth rises from the orchids, a knife shaking in his fist" + " Stay back! ...You killed them? All three? [BLUE](He lowers the knife)[] You're House. Kardagis sent you. She did, didn't she? She didn't think I sold them?",
                               o=[dict(t='Did you?', go=1),
                                  dict(t="She wants to know what happened at the Old Bridge.", go=2)]),
                          dict(t="No! [BLUE](His voice cracks)[] I'd die first. I nearly did.",
                               o=[dict(t="Then tell me what happened at the Old Bridge.", go=2)]),
                          dict(t="The Legion was already there. Waiting. The sergeant said the password before I did, like he was bored of it. Only three people know the week's word: Kardagis, Torja, and whoever sets it. That's the fence, [BLUE]Silas Wren[].",
                               o=[dict(t='And the men hunting you?', go=3)]),
                          dict(t="Not Legion. Too well paid. One of them dropped this. [BLUE](He presses a heavy gold coin into your hand, stamped with an open hand)[] Take it to Kardagis. I'll come home when you tell me it's safe. [BLUE](He hesitates)[] Thanks. Nobody ever came for me before.",
                               o=[dict(t="Go home, Pell. It's safe enough.", go=None, a='GainItem#9511;GainXP#300')]),
                      ]),
                 dict(label='report', at='NG_sewers_kardagis', need=['PlayerHasItems#9511,1'],
                      j="Pell gave me a gold coin dropped by the men who hunted him, and said only Kardagis, Torja and the fence Silas Wren know the weekly password. I must take the coin to Kardagis.",
                      scene=[
                          dict(t=B % "Kardagis turns the coin over in the lamplight. For once she isn't smiling" + " An open golden hand. The [BLUE]Golden Hand[]. Traders, they call themselves. The biggest merchant guild in the kingdoms, with the King's charter in one pocket and the Legion in the other.",
                               o=[dict(t='Why would merchants hunt a runner?', go=1)]),
                          dict(t="Because we smuggle what they want to sell, and cheaper. They've tried to buy us, and tried to starve us. Now someone is selling them our passwords. [BLUE](Her eyes go to the far end of the hall, where the fence Silas Wren counts his coins)[] Pell named names?",
                               o=[dict(t='He said only three people know the word. You, Torja and Silas Wren.', go=2),
                                  dict(t="He named nobody. He's just scared.", go=3)]),
                          dict(t="[BLUE](Very softly)[] Then you'll say nothing of it, to anyone, until I say so. A rat that knows it's been seen runs. A rat that thinks it's safe keeps eating, and we watch where it goes.",
                               o=[dict(t='Understood.', go=4)]),
                          dict(t="[BLUE](She looks at you a long moment)[] You're protecting him, or you're a poor liar. Either way, I like it better than a loud mouth. Keep it shut.",
                               o=[dict(t='Understood.', go=4)]),
                          dict(t="You found the boy, you left three corpses and no witnesses, and you brought me this instead of spending it. That's an Operative, not an Associate. [BLUE](She flicks the coin back to you, then thinks better of it and keeps it)[] Welcome to the long game.",
                               o=[dict(t='The long game?', go=None, a='LoseItems#9511,1')]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 2
        dict(title='The Gilded Ledger', level=10, rep=3,
             brief="If the Golden Hand is buying our secrets, then somewhere there's a ledger that says what they paid and to whom. The Hand's factor in Freetown works out of the upper floors of the [BLUE]Grey Library[]. [BLUE]Arkados[] runs our house in Freetown, and he's been itching to get inside that place for years. Go to him.",
             steps=[
                 dict(label='arkados', at='FT_seventh_arkados',
                      j="Kardagis believes the Golden Hand is buying the House's passwords. I must see Arkados, at the Seventh House hideout in Freetown.",
                      scene=[
                          dict(t="Kardagis's new favourite. [BLUE](Arkados wipes a knife on his sleeve)[] The Hand's man in Freetown is [BLUE]Magister Corvin Hale[]. Soft hands, hard eyes, and a hundred men who'd kill for him because he pays them to. He never writes a thing himself.",
                               o=[dict(t='Then who does?', go=1)]),
                          dict(t="His clerk. [BLUE]Anselm Tully[]. Keeps a copy of every letter Hale sends, because Hale made him swear to, and because Anselm is a coward who wants proof it was never his idea. He works late on the Library's upper floor, by the Hand's traders. Get me those copies.",
                               o=[dict(t='How do I get past the golems?', go=2),
                                  dict(t="I'll get them.", go=None)]),
                          dict(t="You don't. You walk through the front door and tell the Guardian you're there to buy. The Hand never turns away coin. They'd stop me at the gate. You, they haven't learned to hate yet.",
                               o=[dict(t="I'll get them.", go=None)]),
                      ]),
                 dict(label='anselm', at='ekg_s_anselm',
                      j="Anselm Tully, clerk to Magister Corvin Hale of the Golden Hand, keeps copies of Hale's letters. He works on the upper floor of the Grey Library in Freetown, near the Hand's traders.",
                      scene=[
                          dict(t=B % "A thin man in ink-stained cuffs looks up, sees your face, and goes pale" + " You're not a customer. Customers don't look at the doors like that.",
                               o=[dict(t="I want copies of Hale's letters.", go=1),
                                  dict(t="Relax. I'm here to make you an offer.", go=1)]),
                          dict(t="[BLUE](He grips the edge of his desk)[] Do you know what the Magister does to people who... No. No. I can't. He'd know it was me.",
                               o=[dict(t=B % "Put 300 gold on the desk" + " He'll never know. And you'll be richer.", go=2, a='LoseGold#300;SetVariable#ekg_c_seventh_anselm,1', c='PlayerHasGold#300'),
                                  dict(t=B % "Lean close" + " He might hurt you later. I will hurt you now.", go=3, a='SetVariable#ekg_c_seventh_anselm,2'),
                                  dict(t=B % "Reach for your blade" + " Then I'll take them from your desk myself.", go=4, a='SetVariable#ekg_c_seventh_anselm,3')]),
                          dict(t="[BLUE](The coins vanish into his sleeve faster than you would have believed)[] Third drawer. Under the tax receipts. And I never saw you, and you never saw me, and I'm going to be ill.",
                               o=[dict(t=B % "Take the letters", go=None, a='GainItem#9512;GainXP#400')]),
                          dict(t="[BLUE](He is shaking so hard the inkpot rattles)[] Third drawer. Under the tax receipts. Please. Please just go.",
                               o=[dict(t=B % "Take the letters", go=None, a='GainItem#9512;GainXP#400')]),
                          dict(t="[BLUE](He opens his mouth to shout. You are faster. A moment later the clerk is slumped over his ledger, and the letters are in your pack. Nobody on the floor looks up)[]",
                               o=[dict(t=B % "Leave before anyone notices", go=None, a='GainItem#9512;GainXP#400;NPCDespawn#ekg_s_anselm_t')]),
                      ]),
                 dict(label='report', at='FT_seventh_arkados', need=['PlayerHasItems#9512,1'],
                      j="I have copies of Magister Hale's letters. Arkados is waiting at the Freetown hideout.",
                      scene=[
                          dict(t=[('VariableEqual#ekg_c_seventh_anselm,3', "[BLUE](Arkados reads, and whistles)[] And the clerk? ...Quiet work. Hale will know by tonight that someone was there, though. We have less time than I hoped."),
                                  ('VariableEqual#ekg_c_seventh_anselm,2', "[BLUE](Arkados reads, and whistles)[] A frightened clerk is a loose clerk. He'll keep his mouth shut for a week, maybe. Then he'll cry to Hale. Let's be quick."),
                                  (None, "[BLUE](Arkados reads, and whistles)[] Bought, not stolen. Good. A clerk who has taken our gold once will take it twice.")],
                               o=[dict(t='What do they say?', go=1)]),
                          dict(t="Payments. Monthly. To [BLUE]'W.'[], for 'the word of the week'. And here: forty crowns to a Legion clerk for a writ. A thief-taker's writ, with the House named as a nest of murderers. Hale isn't trying to beat us. He's trying to have us hanged.",
                               o=[dict(t="'W.'... Silas Wren.", go=2)]),
                          dict(t="[BLUE](Arkados's face does something ugly)[] Wren. Twenty years he's been fencing for us. Take this to Kardagis. Keep those letters close, too. Paper like that is worth more than gold, to the right people.",
                               o=[dict(t="I'll go to Kardagis.", go=None, a='GainXP#600')]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 3
        dict(title='The Rat', level=12, rep=4, promote=True,
             brief="Arkados sent word. 'W.' [BLUE](Kardagis is quiet for a moment)[] Silas Wren taught me to cut a purse, when I was younger than Pell. He's at his table at the end of the hall, like every night. The House has one law about rats, Operative. But you found him, so you choose how it's kept. Talk to [BLUE]Wren[].",
             steps=[
                 dict(label='wren', at='ekg_s_wren',
                      j="Silas Wren, the House's fence, has been selling the weekly password to Magister Hale. Kardagis left his fate to me. He sits at his table in the New Garand sewers.",
                      scene=[
                          dict(t=B % "A small grey man looks up from his scales, sees the letter in your hand, and puts down his tweezers very carefully" + " Ah. I wondered who she'd send. I hoped it would be her.",
                               o=[dict(t='Why, Wren?', go=1),
                                  dict(t="No speeches. You sold six of us to the Legion.", go=1)]),
                          dict(t="[BLUE](He laughs, without any joy)[] My granddaughter is apprenticed to the Golden Hand, in Freetown. Hale sends me a letter each month with a lock of her hair in it. Each month she is still alive. You tell me what you'd sell.",
                               o=[dict(t="Keep writing to Hale. But from now on, you write what we tell you.", go=2),
                                  dict(t="The House's law is the House's law. Torja can judge you.", go=3),
                                  dict(t="Six in chains. One dead. That's what you sold.", go=4)]),
                          dict(t="[BLUE](He stares at you)[] Lie to the Magister. For the House. [BLUE](Something in his shoulders loosens)[] He'll kill me if he finds out. But he'll kill her anyway, one day, when I'm no use. Yes. Yes, I'll do it. Tell Kardagis... tell her I'm sorry.",
                               o=[dict(t="Tell her yourself, when this is over.", go=None, a='SetVariable#ekg_c_seventh_wren,1;NPCDespawn#ekg_s_wren_t;GainXP#500')]),
                          dict(t="[BLUE](He nods, slowly, and stands)[] Torja. Of course. She'll be fair. That's the worst of it. [BLUE](He walks toward Torja's corner without looking back)[]",
                               o=[dict(t='Go.', go=None, a='SetVariable#ekg_c_seventh_wren,3;NPCDespawn#ekg_s_wren_t;GainXP#300')]),
                          dict(t="[BLUE](He picks up a thin knife from his scales)[] Then let's not keep the House waiting.",
                               o=[dict(t='So be it.', go=None, a='SetVariable#ekg_c_seventh_wren,2;NPCHostile#ekg_s_wren_t')]),
                      ]),
                 dict(label='report', at='NG_sewers_kardagis', need=[],
                      alt_need=[['VariableEqual#ekg_c_seventh_wren,1'], ['VariableEqual#ekg_c_seventh_wren,3'], ['NPCIsDead#ekg_s_wren']],
                      j="The matter of Silas Wren is settled. I must report to Kardagis.",
                      scene=[
                          dict(t=[('VariableEqual#ekg_c_seventh_wren,1', "You turned him. [BLUE](Kardagis smiles slowly)[] A rat that runs our errands into the Magister's own house. Hale will pay for every lie Wren feeds him, and never know he's paying. That, Operative, is how the long game is played."),
                                  ('VariableEqual#ekg_c_seventh_wren,3', "Torja judged him. Exile, with the mark cut into his palm, so no crew in the kingdoms will trust him again. [BLUE](Kardagis looks tired)[] It's the law. I wrote half of it. I don't have to like it."),
                                  (None, "Wren is dead. [BLUE](Kardagis is silent for a while)[] Quick and clean, I hope. He taught me to cut purses, you know. ...The law is the law.")],
                               o=[dict(t="He said Hale holds his granddaughter.", go=1)]),
                          dict(t="Then Hale holds a child as a leash, and pays a Legion clerk to hang my people. [BLUE](She stands)[] The House doesn't forget. You found the rat and you settled it, without asking me to hold your hand. From tonight you're a [BLUE]Shadow[]. Walk softly.",
                               o=[dict(t='I will, Sister.', go=None)]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 4
        dict(title='The Thief-Taker', level=14, rep=6,
             brief="Hale's writ has found a hand to hold it: [BLUE]Captain Odran Brand[], a thief-taker who has never once taken a bribe, which makes him the most dangerous man in the kingdoms. He's gathering his people on the road outside Freetown. [BLUE]Arkados[] is sitting on top of his target. Go to Freetown.",
             steps=[
                 dict(label='arkados', at='FT_seventh_arkados',
                      j="Captain Odran Brand, a thief-taker carrying Hale's writ, is preparing to raid the Seventh House in Freetown. Arkados is waiting for me there.",
                      scene=[
                          dict(t=[('VariableEqual#ekg_c_seventh_wren,1', "Wren's latest letter told Hale we'd moved the Freetown house to the old tannery. [BLUE](Arkados grins)[] Brand's people spent two nights watching an empty building. Now he's angry and tired, and camped by the [BLUE]signpost on the Iron Valley road[], south of the gate."),
                                  (None, "Brand has twelve names on his writ and mine is the first. [BLUE](Arkados doesn't grin)[] He's camped by the [BLUE]signpost on the Iron Valley road[], south of the gate, with his best two. Tomorrow, maybe the day after, he comes through my door.")],
                               o=[dict(t='What kind of man is he?', go=1)]),
                          dict(t="An honest one. [BLUE](He spits)[] The worst kind. He truly believes we're a nest of cutthroats. Half the Legion's officers are in the Hand's pocket, but not Brand. That's why Hale chose him: an honest man doesn't ask who paid for the writ.",
                               o=[dict(t="Then maybe he'd want to know.", go=2),
                                  dict(t="I'll deal with him.", go=None)]),
                          dict(t="[BLUE](Arkados looks at you strangely)[] You'd show a thief-taker our business? ...Well. It's your neck. I'll be here either way.",
                               o=[dict(t="I'll deal with him.", go=None)]),
                      ]),
                 dict(label='brand', at='ekg_s_brand',
                      j="Captain Odran Brand and his thief-takers are camped by the signpost on the Iron Valley road, south of Freetown's gate.",
                      scene=[
                          dict(t=B % "A broad man in a scarred Legion cuirass looks up from a map of Freetown's alleys" + " I know that walk. You're one of Kardagis's. Come to buy me? Better men have tried.",
                               o=[dict(t="Who paid for your writ, Captain?", go=1),
                                  dict(t="I've come to stop you.", go=3)]),
                          dict(t="The Crown. [BLUE](A pause)[] Through the proper clerks. What does it matter? Your House robs honest folk and slits the throats of those who talk.",
                               o=[dict(t=B % "Hand him Hale's letters" + " Read who the proper clerk works for.", go=2, c='PlayerHasItems#9512,1'),
                                  dict(t="It matters. But you wouldn't believe me.", go=3)]),
                          dict(t=B % "Brand reads. Then he reads again, slowly, his lips moving at the part about forty crowns" + " ...A merchant. A merchant bought the Crown's writ, to clear his competition off the board, and made me his broom. [BLUE](He hands the letters back and tears the writ in two)[] This doesn't make your House honest. But I'll be damned if I'm anybody's broom. Tell Kardagis I'll be watching her. And tell Hale I'll be watching him closer.",
                               o=[dict(t='Fair enough, Captain.', go=None, a='SetVariable#ekg_c_seventh_brand,2;NPCDespawn#ekg_s_brand_band;GainXP#1000')]),
                          dict(t="[BLUE](He stands and draws, and his thief-takers do the same)[] Then you'll hang first. In the name of the Crown.",
                               o=[dict(t='Come and take me.', go=None, a='SetVariable#ekg_c_seventh_brand,1;NPCHostile#ekg_s_brand_band')]),
                      ]),
                 dict(label='report', at='FT_seventh_arkados', need=[],
                      alt_need=[['VariableEqual#ekg_c_seventh_brand,2'], ['NPCIsDead#ekg_s_brand']],
                      j="Captain Brand will not raid the Freetown house. I must tell Arkados.",
                      scene=[
                          dict(t=[('VariableEqual#ekg_c_seventh_brand,2', "He tore up the writ? [BLUE](Arkados sits down heavily)[] An honest thief-taker who now hates the Golden Hand more than he hates us. I don't know whether to buy you a drink or have you checked for fever."),
                                  (None, "Brand is dead. [BLUE](Arkados lets out a long breath)[] The Legion will call it murder. Hale will call it proof. But my door stays shut tonight, and my people sleep. Thank you.")],
                               o=[dict(t="Hale won't stop.", go=1)]),
                          dict(t="No. Men like Hale don't stop. They run out of money. [BLUE](A slow smile)[] Tell Kardagis that. She'll understand.",
                               o=[dict(t="I'll tell her.", go=None, a='GainXP#1200;GainGold#800')]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 5
        dict(title='The Golden Cove Job', level=16, rep=7, promote=True,
             brief="'They run out of money.' Arkados is right. Hale keeps the Hand's war chest in the one place he thinks no thief can reach: the vault of the [BLUE]Golden Cove Bank[], in [BLUE]Friguld[]. The bank's director is no man at all. There's a woman in Friguld who knows the way in: [BLUE]Maribel Oste[], a clerk the bank threw out. Find her near the bank doors.",
             steps=[
                 dict(label='maribel', at='ekg_s_maribel',
                      j="Hale keeps the Golden Hand's war chest in the vault of the Golden Cove Bank, in Friguld. Maribel Oste, a dismissed clerk, waits near the bank's doors.",
                      scene=[
                          dict(t=B % "A neat woman in a threadbare good coat does not look at you" + " Kardagis's friend. Don't stand so close. The bank has eyes in the street.",
                               o=[dict(t='You know the way to the vault.', go=1)]),
                          dict(t="I kept the director's appointments for nine years. I know he doesn't sleep, doesn't eat, and doesn't die when you stab him the first time. I know about the barrier and the wards. And I know the five colours of the vault door.",
                               o=[dict(t='Why did they throw you out?', go=2),
                                  dict(t='What do you want?', go=3)]),
                          dict(t="I saw what the director is. [BLUE](Her hands tighten)[] They said I was hysterical and put me on the street with no reference. Nine years.",
                               o=[dict(t='What do you want?', go=3)]),
                          dict(t="A share. A real one. Not a thief's promise.",
                               o=[dict(t="A full share of the vault, on the House's word. The House keeps its word.", go=4, a='SetVariable#ekg_c_seventh_maribel,1'),
                                  dict(t=B % "Give her 500 gold" + " Here's your share now. Don't wait for me.", go=4, a='SetVariable#ekg_c_seventh_maribel,2;LoseGold#500', c='PlayerHasGold#500')]),
                          dict(t="[BLUE](She leans closer and speaks quickly)[] The vault door: [BLUE]red, blue, green, blue, yellow[]. Anything else and the gas comes. The director keeps the Hand's chests past the vault, in his own rooms. Kill him and you can carry out whatever your arms can hold. Kill him properly.",
                               o=[dict(t="Red, blue, green, blue, yellow. I'll remember.", go=None, a='GainXP#800')]),
                      ]),
                 dict(label='director', at='NG_sewers_kardagis', need=['NPCIsDead#H6_director'],
                      j="Maribel gave me the vault door's colours: red, blue, green, blue, yellow. I must get into the Golden Cove Bank in Friguld, kill its director, empty the Golden Hand's war chest and report to Kardagis.",
                      scene=[
                          dict(t=[('VariableEqual#ekg_c_seventh_maribel,1', B % "Kardagis is counting gold. A great deal of gold" + " A demon for a banker. I'll never trust a bank again. Maribel's share went to Friguld this morning, every coin. The House keeps its word, even when no one would know."),
                                  (None, B % "Kardagis is counting gold. A great deal of gold" + " A demon for a banker. I'll never trust a bank again.")],
                               o=[dict(t="How much of it was Hale's?", go=1)]),
                          dict(t=[('VariableEqual#ekg_c_seventh_wren,1', "All of it. [BLUE](She laughs)[] He moved his chest there last month, because Wren wrote to him that we were planning to hit the Library. He carried his own purse into our hands. The Golden Hand's war chest is in my cellar and Hale doesn't have the coin to pay his own guards."),
                                  (None, "Most of it. The Golden Hand's war chest is in my cellar, and Hale doesn't have the coin to pay his own guards this month.")],
                               o=[dict(t="That should slow him down.", go=2)]),
                          dict(t="It should. It'll also make him desperate, and desperate men are careless and cruel. [BLUE](She presses a heavy purse into your hands)[] The biggest job this House has pulled in a generation, and you walked out of it breathing. [BLUE]Master Thief[]. Say it out loud, you've earned it.",
                               o=[dict(t='Master Thief.', go=None)]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 6
        dict(title='Blood Price', level=18, rep=10, promote=True,
             brief="[BLUE](Kardagis is white with fury)[] [BLUE]Pell[] didn't come back from a run last night. This morning there was a gold coin with an open hand on it nailed to Torja's door. Hale wants his money back, and he knows what we value more than money. [BLUE]Torja[] has the note. Go to her.",
             steps=[
                 dict(label='torja', at='NG_sewers_torja',
                      j="Pell has been taken by the Golden Hand. Torja has Hale's note.",
                      scene=[
                          dict(t=B % "Torja hands you a scrap of expensive paper. Her hands are perfectly steady, which is somehow worse" + " 'The boy for the Friguld gold. Bring it alone to the old smuggler hideout in the [BLUE]Northern Inori Desert[]. Or he goes back to the House in pieces.'",
                               o=[dict(t="We're not paying.", go=1),
                                  dict(t="Who holds him?", go=2)]),
                          dict(t="No. We're not. [BLUE](She almost smiles)[] Pay a kidnapper once and every child in the House is worth a ransom. Go and get him.",
                               o=[dict(t="Who holds him?", go=2)]),
                          dict(t="Hale's hired knives. The woman who leads them is called [BLUE]Sable[]. She's killed three of ours that I know of and seven I suspect. The hideout is haunted, they say, which is why nobody goes there. [BLUE](A pause)[] Bring him home, Master Thief.",
                               o=[dict(t="I'll bring him home.", go=None)]),
                      ]),
                 dict(label='pell', at='ekg_s_pell_cap',
                      need=['NPCIsDead#ekg_s_sable', 'NPCIsDead#ekg_s_knife1', 'NPCIsDead#ekg_s_knife2'],
                      j="Pell is held in the abandoned smuggler hideout in the Northern Inori Desert, by Sable and her Gilded Knives. I must kill them and free him.",
                      scene=[
                          dict(t=B % "You cut Pell's ropes. He falls, gets up, falls again, and then just holds on to your arm" + " I knew. I knew someone would come. I didn't tell them anything. I didn't.",
                               o=[dict(t="I know you didn't. Can you walk?", go=1)]),
                          dict(t="I can run, if it means getting out of here. [BLUE](He swallows)[] Listen. Sable talked, when she thought I was asleep. Hale is scared. He's barricaded himself in the Grey Library with the last of his money. And he called Kardagis something. He called her [BLUE]'the Seventh'[]. Like it was a title.",
                               o=[dict(t="Let's get you home. I'll ask her.", go=None, a='GainXP#1500')]),
                      ]),
                 dict(label='report', at='NG_sewers_kardagis',
                      j="Pell is free. Before we left he told me that Hale called Kardagis 'the Seventh'. I must report to her.",
                      scene=[
                          dict(t=B % "Pell is asleep on Torja's bed with his boots on. Kardagis stands over him for a long moment before she speaks" + " Sable?",
                               o=[dict(t='Dead. Her knives too.', go=1)]),
                          dict(t="Good. [BLUE](She turns to you)[] You went into a haunted hole for a runner nobody would have missed. That's why the House exists. Not the gold. That. You are the [BLUE]Hand of the House[] now, my right hand.",
                               o=[dict(t="Hale called you 'the Seventh'.", go=2)]),
                          dict(t="[BLUE](The smallest pause)[] Did he. Hale says a great many things. Finish him first. Then ask me again.",
                               o=[dict(t="I'll hold you to that.", go=None)]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 7
        dict(title='The Long Game', level=20, rep=12,
             brief="Hale has run out of money, allies and places to hide. He's shut himself in the [BLUE]Grey Library[] with the last swords he could afford. [BLUE]Arkados[] is gathering our Freetown people to cause a scene at the front gate. Go to him. Then end it, one way or another.",
             steps=[
                 dict(label='arkados', at='FT_seventh_arkados',
                      j="Magister Hale is barricaded in the Grey Library. Arkados is gathering the Freetown house to create a diversion.",
                      scene=[
                          dict(t="[BLUE](Arkados is strapping on more knives than seems sensible)[] At sundown half of Freetown's house starts a brawl at the Library gate. The Hand's golems come out, the guards come out, and you walk in behind them. Hale's upstairs, on the traders' floor, with two enforcers who cost him everything he had left.",
                               o=[dict(t='Anything else I should know?', go=1)]),
                          dict(t=[('VariableEqual#ekg_c_seventh_brand,2', "Brand sent a runner, of all things. 'The Legion has opened an inquiry into Magister Hale's writ.' [BLUE](Arkados laughs)[] Hale knows it too. He's got nowhere left to run, which makes him dangerous. Go."),
                                  (None, "Only that a cornered man bites. Hale's got nothing left to lose, which makes him dangerous. Go.")],
                               o=[dict(t="Sundown, then.", go=None)]),
                      ]),
                 dict(label='hale', at='ekg_s_hale',
                      j="Magister Corvin Hale waits on the traders' floor of the Grey Library in Freetown, with two enforcers.",
                      scene=[
                          dict(t=B % "A tall man in crimson silk pours two cups of wine and pushes one across the table toward you" + " The Hand of the House. Sit. Drink. It isn't poisoned. Poison is for people I can afford to replace.",
                               o=[dict(t="You took a child hostage.", go=1),
                                  dict(t="Say what you have to say.", go=1)]),
                          dict(t="[BLUE](He shrugs)[] I took a piece off the board. So did you, when you emptied my vault. Let's not pretend either of us plays for love. [BLUE](He leans forward)[] Here is my offer. Kardagis is the Seventh. There is no mysterious boss behind her. There never was. Kill her and the House is yours, with the Golden Hand as your partner instead of your enemy.",
                               o=[dict(t="I'd never trust you.", go=2),
                                  dict(t="How do you know she's the Seventh?", go=3)]),
                          dict(t="Trust? Who said anything about trust? I'm offering you a throne.",
                               o=[dict(t="Your war chest is gone, and your 'W.' has lied to you for months. Sign Freetown's trade over to the House and take the next ship south.", go=4, c='VariableEqual#ekg_c_seventh_wren,1'),
                                  dict(t="The Legion has opened an inquiry into your writ. Sign Freetown's trade over to the House and take the next ship south, before Brand comes for you.", go=4, c='VariableEqual#ekg_c_seventh_brand,2;VariableGreater#ekg_c_seventh_wren,1'),
                                  dict(t="No. I'm here to end you.", go=5)]),
                          dict(t="Because I've been paying for the answer for three years. Everyone in the House thinks the boss is somewhere else, watching. She built that story so nobody would put a knife in her back. Clever. [BLUE](He smiles)[] So. Do we have a deal?",
                               o=[dict(t="No deal.", go=2)]),
                          dict(t=B % "Hale looks at you for a long time. Then, very slowly, he takes a pen and signs" + " ...You'd have made a fine merchant. [BLUE](He stands, and his enforcers step back)[] The trade is yours. Tell Kardagis the long game was hers. I'll be on the next ship. [BLUE](At the door he stops)[] Wren's granddaughter is at the Hand's counting-house on Salt Street. Take her. I have no more use for leashes.",
                               o=[dict(t='Go.', go=None, a='SetVariable#ekg_c_seventh_hale,2;NPCDespawn#ekg_s_hale_band;GainXP#3000')]),
                          dict(t="[BLUE](Hale sighs and sets down his cup)[] What a waste. [BLUE](His enforcers draw)[]",
                               o=[dict(t='Yes. It is.', go=None, a='SetVariable#ekg_c_seventh_hale,1;NPCHostile#ekg_s_hale_band')]),
                      ]),
                 dict(label='report', at='NG_sewers_kardagis', need=[],
                      alt_need=[['VariableEqual#ekg_c_seventh_hale,2'], ['NPCIsDead#ekg_s_hale']],
                      j="Magister Hale is finished. I must report to Kardagis and ask her about 'the Seventh'.",
                      scene=[
                          dict(t=[('VariableEqual#ekg_c_seventh_hale,2', "Freetown's trade, signed and sealed. [BLUE](Kardagis holds the paper up to the lamp as if it might vanish)[] Twenty years the Hand has been trying to put us in the ground, and you made their factor sign us their business and sail away. The songs they'll sing about this will be terrible. I'll enjoy every one."),
                                  (None, "Hale is dead. [BLUE](Kardagis lets out a breath she seems to have been holding for years)[] The Golden Hand will send another factor, in time. He'll remember what happened to this one.")],
                               o=[dict(t="Hale said you're the Seventh. That there's no boss behind you.", go=1)]),
                          dict(t="[BLUE](She is quiet for a long time)[] I promised to tell you. And I will. Not tonight. Come back when you're ready. When you're [BLUE]level 21[] and you've done the House's work, [BLUE]14 contracts[] of it. It's not a story for someone who's still in a hurry.",
                               o=[dict(t="I'll come back.", go=None, a='GainXP#3000;GainGold#3000')]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 8
        dict(title='The Seventh Seat', level=21, rep=14, promote=True, master=True,
             brief="Sit down. [BLUE](Kardagis pours two cups, and for once they are both for drinking)[] You asked me a question. Ask it again, and I'll answer it properly.",
             steps=[
                 dict(label='truth', at='NG_sewers_kardagis',
                      j="Kardagis has promised to tell me the truth about 'the Seventh'.",
                      scene=[
                          dict(t="Six founders built the House, a hundred years ago. Six seats. The seventh seat was left empty on purpose: the boss nobody sees, who can't be bribed or knifed or hanged because nobody knows who it is. [BLUE](She sips)[] Whoever holds the House holds the seventh seat. For fifteen years, that's been me.",
                               o=[dict(t="So all those orders from 'the boss'...", go=1)]),
                          dict(t="Mine. Every one. A shadow is safer than a woman. [BLUE](She sets down the cup)[] And I'm tired. I want to sit in a sunny window in Varsilia and cheat old men at cards. The House needs someone who can play the long game and still go into a haunted hole for a runner. That's you.",
                               o=[dict(t="What must I do?", go=2)]),
                          dict(t="What every Seventh has done. Get the blessing of the two who keep the House honest: [BLUE]Torja[], who keeps its debts, and [BLUE]Arkados[], who keeps its blades. Then steal something no one can steal. Every Seventh takes one prize from the [BLUE]White King[], the dragon in the halls beneath [BLUE]Icemist[]. Few come back. The ones who do, sit here.",
                               o=[dict(t="Then I'll start with Torja.", go=None, a='GainXP#1000')]),
                      ]),
                 dict(label='torja', at='NG_sewers_torja',
                      j="To take the seventh seat I need the blessings of Torja and Arkados, then a prize from the White King's hoard beneath Icemist.",
                      scene=[
                          dict(t=B % "Torja opens her greasy ledger to the very first page, which is blank except for six old names, and a seventh line left empty" + " Nobody's ever seen this page but Kardagis and me. [BLUE](She dips her pen)[] The House owes you, and you owe the House. That's a clean tally. Torja gives her blessing.",
                               o=[dict(t="Thank you, Torja.", go=1)]),
                          dict(t="Don't thank me. Come back alive, so I don't have to cross it out.",
                               o=[dict(t="I'll come back.", go=None, a='GainXP#1000')]),
                      ]),
                 dict(label='arkados', at='FT_seventh_arkados',
                      j="Torja has given her blessing. Next, Arkados in Freetown.",
                      scene=[
                          dict(t="[BLUE](Arkados stares, then laughs until he has to hold on to the table)[] Kardagis? The Seventh? Fifteen years I've been taking orders from a ghost that sat across from me at supper. [BLUE](He wipes his eyes)[] You have Freetown's blades. Try not to get killed by that lizard before I can say I knew you when.",
                               o=[dict(t="I'll do my best.", go=None, a='GainXP#1000')]),
                      ]),
                 dict(label='hoard', at='NG_sewers_kardagis', need=['NPCIsDead#IM_white_king'],
                      j="Both keepers have given their blessing. I must take a prize from the hoard of the White King, the dragon in the halls beneath Icemist, and return to Kardagis.",
                      scene=[
                          dict(t=B % "The whole House is gathered in the sewer hall. You lay a scale of ice-white dragonhide, the size of a shield, on Kardagis's table, and the room goes silent" + " The White King. [BLUE](Kardagis's voice carries to every corner)[] Brothers, Sisters. You've all wondered who the boss is. Tonight you get to see.",
                               o=[dict(t=B % "Stand beside her", go=1)]),
                          dict(t=[('VariableEqual#ekg_c_seventh_wren,1', "[BLUE](At the back of the hall, Silas Wren stands with a thin girl in a Golden Hand apprentice's coat, and bows his head to you)[] The seventh seat is not a chair. It is a promise: that the House looks after its own, and never forgets a debt. Do you make it?"),
                                  (None, "The seventh seat is not a chair. It is a promise: that the House looks after its own, and never forgets a debt. Do you make it?")],
                               o=[dict(t='I make it.', go=2)]),
                          dict(t=[('VariableEqual#ekg_c_seventh_maribel,1', "[BLUE](Pell cheers first, too loudly. Maribel Oste, in a new coat, is standing by Torja, and raises a cup)[] Then the seat is yours, [BLUE]Master of the House[]. And I'm going to find a sunny window. Don't write."),
                                  (None, "[BLUE](Pell cheers first, too loudly, and then the whole House is shouting)[] Then the seat is yours, [BLUE]Master of the House[]. And I'm going to find a sunny window. Don't write.")],
                               o=[dict(t="Thank you, Kardagis. For everything.", go=None)]),
                      ]),
             ]),
    ])

STORIES = {'warriors': WARRIORS, 'seventh': SEVENTH}
