"""Guild main quest lines (v75 story engine data; deobf/GUILD_EXPANSION_SPEC.md §10).

A story is a list of chapters. A chapter is offered by the guild leader (hub node 720) once the player has the
level, the contracts (rep) and the previous chapter; accepting starts its first step. Each step is a scene at one
NPC (an existing conversation file or a new character added by the story) that plays when the step is current and
its `need` conditions hold; an option with go=None finishes the step (next step, or the chapter end with its
promotion). `jump` names another step of the same chapter.

Beat:  {'t': text | [(cond, text), ..., (None, default)], 'o': [option, ...]}
Option: {'t': text, 'go': beat index | None (finish step) | 'hold' (end, step stays), 'a': actions, 'c': conds,
         'jump': step label}
Text markup: [BLUE]..[] narration.  Choice variables: ekg_c_<g>_<key>.
"""

W_NPCS = [
    # --- chapter 1: Brann in the farmlands, then home at the guild hall
    dict(id='ekg_w_brann_h8', map='H8', at=(2196, 1096), kind='static', name='Brann Holloway', sprite='male_brown_12',
         portrait=18, show=('1.1', '1.3')),
    dict(id='ekg_w_scout1', group='ekg_w_scouts', map='H8', at=(2188, 1384), kind='foe', spawn='guild_mercenary', name='Crimson Scout',
         faction='bandits', show=('1.1', '1.2')),
    dict(id='ekg_w_scout2', group='ekg_w_scouts', map='H8', at=(2387, 1421), kind='foe', spawn='guild_mercenary', name='Crimson Scout',
         faction='bandits', show=('1.1', '1.2')),
    dict(id='ekg_w_scout3', group='ekg_w_scouts', map='H8', at=(2623, 1533), kind='foe', spawn='bandit_male_assasin', name='Crimson Scout Leader',
         faction='bandits', show=('1.1', '1.2')),
    dict(id='ekg_w_brann', map='NG_warriors', at=(448, 602), kind='static', name='Brann Holloway', sprite='male_brown_12',
         portrait=18, show=('1.3', None)),
    # --- chapter 2: Lyse in Freetown, Garrick on the Rhoneis Plains
    dict(id='ekg_w_lyse', map='FT', at=(1351, 783), kind='static', name='Lyse Corwen', sprite='female_red_1', portrait=12,
         gender='f', show=('2.2', '2.4')),
    dict(id='ekg_w_garrick', map='F10', at=(2892, 1024), kind='foe', spawn='outlaw_chief', name='Garrick the Knife',
         faction='bandits', show=('2.3', '2.3')),
    dict(id='ekg_w_cut1', map='F10', at=(2860, 1060), kind='foe', spawn='bandit_male_assasin', name='Crimson Cutthroat',
         faction='bandits', show=('2.3', '2.3')),
    dict(id='ekg_w_cut2', map='F10', at=(2920, 990), kind='foe', spawn='bandit_male_assasin', name='Crimson Cutthroat',
         faction='bandits', show=('2.3', '2.3')),
    dict(id='ekg_w_lyse_ng', map='NG_warriors', at=(425, 635), kind='static', name='Lyse Corwen', sprite='female_red_1',
         portrait=12, gender='f', show=('3.1', None), cond='VariableEqual#ekg_c_warriors_lyse,1'),
    # --- chapter 3: Oreth the Binder in the Trollfens
    dict(id='ekg_w_oreth', map='E8', at=(1624, 421), kind='talker', spawn='I9_necromancer', name='Oreth the Binder',
         show=('3.1', '3.1')),
    # --- chapter 4: Captain Sera Blackwell at Sanctuary Peak
    dict(id='ekg_w_sera', map='D13', at=(1045, 707), kind='talker', spawn='friguld_captain', name='Captain Sera Blackwell',
         show=('4.2', '4.2'), group='ekg_w_sera_band'),
    dict(id='ekg_w_sera_g1', map='D13', at=(1010, 740), kind='talker', spawn='knight_hostile', name='Crimson Sword',
         show=('4.2', '4.2'), group='ekg_w_sera_band', talk=False),
    dict(id='ekg_w_sera_g2', map='D13', at=(1080, 680), kind='talker', spawn='knight_hostile', name='Crimson Sword',
         show=('4.2', '4.2'), group='ekg_w_sera_band', talk=False),
    # --- chapter 5: the courier on the Imperial Coast
    dict(id='ekg_w_maddoc', map='I8', at=(1201, 959), kind='foe', spawn='outlaw_king', name='Maddoc the Courier',
         faction='bandits', show=('5.1', '5.1')),
    dict(id='ekg_w_esc1', map='I8', at=(1170, 990), kind='foe', spawn='rogue_melee_12', name='Crimson Escort',
         faction='bandits', show=('5.1', '5.1')),
    dict(id='ekg_w_esc2', map='I8', at=(1230, 930), kind='foe', spawn='rogue_archer_12', name='Crimson Escort',
         faction='bandits', show=('5.1', '5.1')),
    # --- chapter 6: the beastbinder in the Sunken Citadel
    dict(id='ekg_w_handler', map='H3_cave', at=(316, 1545), kind='foe', spawn='forsaken_mage', name='Crimson Beastbinder',
         faction='enemy', show=('6.2', '6.2')),
    # --- chapter 7: Varrek Dunmore at the Imperial Fortress
    dict(id='ekg_w_varrek', map='J9_castle', at=(870, 1560), kind='talker', spawn='forsaken_knight2', name='Varrek Dunmore',
         show=('7.2', '7.2'), group='ekg_w_company'),
    dict(id='ekg_w_lt1', map='J9_castle', at=(980, 1535), kind='talker', spawn='forsaken_knight', name='Crimson Lieutenant',
         show=('7.2', '7.2'), group='ekg_w_company', talk=False),
    dict(id='ekg_w_lt2', map='J9_castle', at=(763, 1599), kind='talker', spawn='forsaken_knight', name='Crimson Lieutenant',
         show=('7.2', '7.2'), group='ekg_w_company', talk=False),
]

W_ITEMS = [
    (9501, 'Crimson Sash', 'A torn red sash, stiff with dried blood. Sewn inside: the sigil of a clenched gauntlet.', 'letters'),
    (9502, "Vane's Letters", "Sealed letters from Lord Aldric Vane to 'V.D.', promising coin for 'beast-work' along the King's roads.", 'letters'),
]

B = '[BLUE](%s)[]'

WARRIORS = dict(
    npcs=W_NPCS, items=W_ITEMS,
    idle={  # default lines of the new characters when no scene is due
        'ekg_w_brann_h8': "[BLUE](Brann is binding his leg with a strip of cloak)[] I'll live. Go on.",
        'ekg_w_brann': [('VariableEqual#ekg_st_warriors,100', "Guild Master. [BLUE](Brann grins)[] Never thought I'd live to say that to someone I pulled out of a ditch. Well. You pulled me."),
                        ('VariableGreater#ekg_st_warriors,{7.2}', "Varrek... [BLUE](He shakes his head)[] Twenty years I called him brother. Don't mind me."),
                        (None, "[BLUE](Brann Holloway, scout of the Warriors' Guild, is sharpening a short sword)[] The leg aches when it rains. It rains a lot in New Garand.")],
        'ekg_w_lyse': "[BLUE](Lyse watches the door more than her drink)[] Not here. Not now.",
        'ekg_w_lyse_ng': "[BLUE](Lyse is going through the guild's supply ledgers, frowning)[] Your quartermaster couldn't count to ten with both hands. I'm fixing it. You're welcome.",
        'ekg_w_oreth': "Leave me be.",
        'ekg_w_sera': "Keep walking, guildling.",
        'ekg_w_varrek': "...",
    },
    chapters=[
        # ------------------------------------------------------------------ 1
        dict(title='Blood on the Road', level=8, rep=2, promote=True,
             brief="A patrol of ours never came back from the farmlands south of the city. [BLUE]Brann Holloway[] led it; he's been walking those roads for twenty years and he doesn't get lost. Monsters, the farmers say. I want to hear it from Brann, or from what's left of him. [BLUE]The New Garand Farmlands[], recruit. Find them.",
             steps=[
                 dict(label='brann', at='ekg_w_brann_h8',
                      j="Brann Holloway's patrol vanished in the New Garand Farmlands. Sergeant Daukar wants to know what happened.",
                      scene=[
                          dict(t=B % "A grey-bearded man sits against a broken cart, a crossbow bolt snapped off in his thigh" + " Guild colours. Thank the Three. Is Daukar with you? No... just you. Right.",
                               o=[dict(t='What happened here?', go=1),
                                  dict(t="Hold still. Let me see that leg.", go=1, a='GainXP#50')]),
                          dict(t="Monsters, the farmers'll say. There wasn't a beast among them. Men, a dozen, red sashes, crossbows. They knew our route and they knew our numbers. Went for the carts first, then for us. Took the guild seals off the dead. [BLUE](He spits)[] Seals. What does a cutthroat want with guild seals?",
                               o=[dict(t='Are they still around?', go=2),
                                  dict(t='Why take the seals?', go=3)]),
                          dict(t="Three of them stayed behind to pick the bodies clean. I heard them laughing. South and east of here, toward the old fields. I can't walk and you can. Make them stop laughing.",
                               o=[dict(t="I'll deal with them.", go=None),
                                  dict(t='Why take the seals?', go=3)]),
                          dict(t="Put a guild seal on a dead minotaur and nobody asks who killed it. Put one on a burned farm and everyone asks why the guild didn't come. You follow? Somebody wants the Warriors' Guild to look useless. Three of them are still out there, to the south-east. Start with them.",
                               o=[dict(t="I'll deal with them.", go=None)]),
                      ]),
                 dict(label='scouts', at='ekg_w_brann_h8',
                      need=['NPCIsDead#ekg_w_scout1', 'NPCIsDead#ekg_w_scout2', 'NPCIsDead#ekg_w_scout3'],
                      j="Three of the ambushers stayed behind in the farmlands, south-east of Brann. I must kill them and return to him.",
                      scene=[
                          dict(t="I heard it from here. [BLUE](Brann looks at what you carry)[] Their leader wore this? Let me see.",
                               o=[dict(t=B % "Show him the red sash you took from the leader", go=1, a='GainItem#9501')]),
                          dict(t="Stitched inside. A clenched gauntlet. [BLUE](His face goes grey, and not from the wound)[] I know that mark. Take it to Daukar. Tell her Brann said: it's the Company. She'll know. I'll limp home on my own; it's what I'm good at.",
                               o=[dict(t='Can you make it back?', go=2),
                                  dict(t="I'll tell her.", go=None, a='GainXP#300')]),
                          dict(t="I've walked out of worse with fewer legs. Go.",
                               o=[dict(t="I'll tell her.", go=None, a='GainXP#300')]),
                      ]),
                 dict(label='report', at='NG_warriors_daukar', need=['PlayerHasItems#9501,1'],
                      j="Brann recognised the mark on the sash: 'the Company'. I must take it to Sergeant Daukar.",
                      scene=[
                          dict(t="Brann's alive? Good. That old goat owes me money. [BLUE](She takes the sash, and her jaw tightens at the gauntlet)[] The Crimson Company.",
                               o=[dict(t='Who are they?', go=1)]),
                          dict(t="Sellswords. The best-paid in the four kingdoms, and the worst. Their commander is [BLUE]Varrek Dunmore[]. Twenty years ago he was a sergeant of this guild, standing where I stand. He sold his oath to the highest bidder and we struck his name from the wall.",
                               o=[dict(t='Why would he attack guild patrols?', go=2),
                                  dict(t='Brann seemed to know the mark.', go=3)]),
                          dict(t="Because every lord who stops trusting the Guild starts buying the Company. Burn a few farms, leave our seals in the ashes, and the King's council asks why he still pays for us. Varrek always did understand coin better than honour.",
                               o=[dict(t='What do we do?', go=4)]),
                          dict(t="Brann served under Varrek. They were brothers, near enough. Don't ask him about it unless you want your nose broken. [BLUE](Almost gently)[] He's the reason Brann walks the roads alone.",
                               o=[dict(t='What do we do?', go=4)]),
                          dict(t="You did well, and you kept your head. That's a soldier, not a recruit. [BLUE](She hands you a ring)[] Keep your eyes open and your contracts filled. When the Company moves again, I'll need you.",
                               o=[dict(t='I stand ready, Sergeant.', go=None, a='LoseItems#9501,1')]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 2
        dict(title='Red Sashes', level=10, rep=3,
             brief="The Company recruits in Freetown; half the port's taverns are full of their coin. [BLUE]Toel[] runs our guildhouse there and he keeps his ears open. Go to him. Find out who pays the Company, and what for.",
             steps=[
                 dict(label='toel', at='FT_warriors_toel',
                      j="Daukar sent me to Toel, at the Warriors' Guildhouse in Freetown, to learn who pays the Crimson Company.",
                      scene=[
                          dict(t="Daukar's runner told me you'd come. Sit. Freetown is crawling with red sashes this season; the Company pays three silver a day and asks no questions. Most of my own recruits walked across the square and signed with them.",
                               o=[dict(t='Anyone who might talk?', go=1)]),
                          dict(t="One. A woman named [BLUE]Lyse Corwen[]. The Company's quartermaster, if the drunks are right. For a week she's been asking, quietly, what the Guild does with deserters. Evenings she waits on the square by the [BLUE]watch post[], near the Generous King, pretending not to wait for anyone. Be gentle. Frightened people bolt.",
                               o=[dict(t="I'll find her.", go=None)]),
                      ]),
                 dict(label='lyse', at='ekg_w_lyse',
                      j="Toel says a Company quartermaster, Lyse Corwen, wants out. She waits on the square by the watch post in Freetown, near the Generous King.",
                      scene=[
                          dict(t=B % "A thin woman with ink-stained fingers looks up sharply" + " Guild. It's on you like a smell. Sit down before someone notices you standing over me.",
                               o=[dict(t='Toel says you want out of the Company.', go=1),
                                  dict(t='I hear you ask a lot of questions.', go=1)]),
                          dict(t="I kept Varrek's books for six years. Pay, rations, bribes. Then the entries started saying [BLUE]'beast-work'[], paid by a lord's steward, in gold. I asked what it meant. The next morning my ledger was gone and [BLUE]Garrick the Knife[] was sleeping outside my door.",
                               o=[dict(t='Who is Garrick?', go=2)]),
                          dict(t="Varrek's dog. He took my ledger to sell it back to Varrek with my name on it. He's camped on the [BLUE]Rhoneis Plains[], east, with two of his friends, waiting for his pay. Bring me that ledger and I'll tell you everything in it. Every name.",
                               o=[dict(t="Stay here. I'll bring it back.", go=None)]),
                      ]),
                 dict(label='garrick', at='ekg_w_lyse', need=['NPCIsDead#ekg_w_garrick'],
                      j="Garrick the Knife took Lyse's ledger. He's camped on the Rhoneis Plains, far to the east of Freetown's farmland, with two cutthroats.",
                      scene=[
                          dict(t=B % "You set the oilcloth ledger you took from Garrick on the table. Lyse lets out a long breath" + " He's dead? Good. Look here. And here.",
                               o=[dict(t='Tell me what it says.', go=1)]),
                          dict(t="Forty payments in two years from [BLUE]Lord Aldric Vane[]'s steward. Vane sits on the King's council. And these: 'O. the Binder, Trollfens, for beasts delivered.' Varrek isn't hiring swords to fight monsters. He is buying the monsters. Somebody named Oreth drives them onto the roads, the Company 'saves' the villages, and Vane tells the King the Guild is finished.",
                               o=[dict(t="That's everything I need.", go=2)]),
                          dict(t="Then here is what I need. Varrek will know by tomorrow that Garrick is dead. What happens to me now?",
                               o=[dict(t="Come to New Garand. The Guild protects those who help it.", go=3, a='SetVariable#ekg_c_warriors_lyse,1'),
                                  dict(t=B % "Give her 200 gold" + " Take this and disappear. Somewhere far.", go=4, a='SetVariable#ekg_c_warriors_lyse,2;LoseGold#200', c='PlayerHasGold#200'),
                                  dict(t="You kept Varrek's books while he murdered our people. The Freetown watch can have you.", go=5, a='SetVariable#ekg_c_warriors_lyse,3;GainGold#300')]),
                          dict(t="[BLUE](She looks at you for a long moment)[] ...All right. New Garand. If your Sergeant hangs me, I'm haunting you.",
                               o=[dict(t='Tell Toel I sent you. He will get you there safely.', go=None)]),
                          dict(t="[BLUE](She closes her hand over the coins)[] You're a strange sort of soldier. Thank you. If you ever need a ledger read, I'll be... somewhere.",
                               o=[dict(t='Go.', go=None)]),
                          dict(t="[BLUE](She stares at you, then laughs, hollow)[] Of course. You're all the same, guild or company. [BLUE](The watch takes her; the captain presses a bounty into your hand)[]",
                               o=[dict(t='...', go=None)]),
                      ]),
                 dict(label='report', at='FT_warriors_toel',
                      j="Lyse's ledger names Lord Aldric Vane of the King's council as the Company's paymaster, and 'Oreth the Binder' in the Trollfens. I must report to Toel.",
                      scene=[
                          dict(t=[('VariableEqual#ekg_c_warriors_lyse,1', "Lyse Corwen is on a cart to New Garand with two of my best. You did right by her. The Guild keeps its word or it is nothing."),
                                  ('VariableEqual#ekg_c_warriors_lyse,3', "The watch hanged nobody yet, but they will. [BLUE](Toel looks away)[] She came to us. Remember that, the next time someone does."),
                                  (None, "Gone, eh? Best for her, maybe. Varrek doesn't forgive.")],
                               o=[dict(t='Vane pays the Company. And someone called Oreth drives the beasts.', go=1)]),
                          dict(t="A council lord. Beasts on a leash. [BLUE](He is quiet for a while)[] Daukar needs to hear this from you, not from a letter. And go carefully. If Vane has the King's ear, then from here on we are the ones on trial.",
                               o=[dict(t="I'll go to Daukar.", go=None, a='GainXP#600')]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 3
        dict(title='The Beast-Binder', level=12, rep=4, promote=True,
             brief="Oreth the Binder. A hedge-mage with a knack for chaining beasts to his will, and the Company's leash on every troll in the fens. He hides in [BLUE]the Trollfens[], west of here. Find him. What you do with him depends on what he tells you, but the trolls stop raiding either way.",
             steps=[
                 dict(label='oreth', at='ekg_w_oreth',
                      j="Oreth the Binder, the hedge-mage who drives beasts for the Crimson Company, hides in the Trollfens.",
                      scene=[
                          dict(t=B % "A gaunt man in a filthy robe stands among bones, a carved totem hanging from his neck" + " A guild blade. How quaint. Did Varrek finally stop paying you people too?",
                               o=[dict(t='You set monsters on innocent villages.', go=1),
                                  dict(t='Tell me about the Company, and you might live.', go=2)]),
                          dict(t="I set nothing. I ask, politely, in a language the trolls understand. What they do on the road is their nature. What the Company does after is theirs. I am just a craftsman.",
                               o=[dict(t='Tell me about the Company, and you might live.', go=2),
                                  dict(t="A craftsman who's about to die.", go=None, a='NPCHostile#ekg_w_oreth_t;SetVariable#ekg_c_warriors_oreth,2')]),
                          dict(t="[BLUE](He fingers the totem)[] Live? Very well. The real leash isn't mine. It is [BLUE]King Gurguth[], the troll king in his cave in these fens. Varrek gave me a binding stone for him. While Gurguth serves, every troll in the fens serves. Kill the king and the leash snaps.",
                               o=[dict(t='Leave the fens. If I see you again, you die.', go=None, a='NPCDespawn#ekg_w_oreth_t;SetVariable#ekg_c_warriors_oreth,1;GainXP#400'),
                                  dict(t="Thank you. Now you die.", go=None, a='NPCHostile#ekg_w_oreth_t;SetVariable#ekg_c_warriors_oreth,2')]),
                      ]),
                 dict(label='gurguth', at='NG_warriors_daukar', need=['NPCIsDead#king_gurguth'],
                      j="The binding that holds the trolls runs through King Gurguth, in Gurguth Cave in the Trollfens. I must kill him, then report to Daukar.",
                      scene=[
                          dict(t=[('VariableEqual#ekg_c_warriors_oreth,1', "You let the Binder go? [BLUE](She considers)[] Mercy is a soldier's right, when it costs nothing. Pray it cost nothing. And Gurguth?"),
                                  (None, "The Binder's dead and the fens are quiet. And Gurguth?")],
                               o=[dict(t='The troll king is dead. The leash is broken.', go=1)]),
                          dict(t="Then Varrek has lost his beasts, and Vane has lost his excuse. [BLUE](She stands straighter)[] You have faced a troll king and walked back. That makes you a Veteran of the Warriors' Guild. Brann will want to buy you a drink; let him, he never does.",
                               o=[dict(t='Thank you, Sergeant.', go=None)]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 4
        dict(title="The Giants' Price", level=14, rep=6,
             brief="A rider came from Nivarian. [BLUE]Morg[], the warmaster of our hall there, asks for you by name, which means word of you has travelled. He wouldn't say more in a letter. Go to him in [BLUE]Nivarian[].",
             steps=[
                 dict(label='morg', at='NI_warriors_morg',
                      j="Warmaster Morg of the Nivarian hall asked for me by name.",
                      scene=[
                          dict(t="So you're Daukar's troll-killer. [BLUE](Morg looks you over like a horse he's thinking of buying)[] You'll do. Listen. The Company has sent gold up [BLUE]Sanctuary Peak[]. The hill giants up there have a new chief, and he has started wearing a red sash.",
                               o=[dict(t='The Company is buying giants now?', go=1)]),
                          dict(t="Beasts were cheap. Giants are expensive, and a giant with a warband doesn't need a Binder. The one carrying the gold is [BLUE]Captain Sera Blackwell[]. She was a Mercian officer before the Company; a real soldier. Stop the deal.",
                               o=[dict(t="I'll go to Sanctuary Peak.", go=None)]),
                      ]),
                 dict(label='sera', at='ekg_w_sera',
                      j="Captain Sera Blackwell is buying the hill giants of Sanctuary Peak for the Crimson Company.",
                      scene=[
                          dict(t=B % "A woman in dented Mercian plate turns from the cliff's edge, two swords at her back" + " The guild's troll-killer. Varrek said you'd come. He also said you'd be taller.",
                               o=[dict(t="The deal is off. Go home, Captain.", go=1),
                                  dict(t="You're a real soldier, Morg says. Why serve Varrek?", go=2)]),
                          dict(t="Home? The Company is my home. The Guild pays in speeches; Varrek pays in gold, and he pays on time. [BLUE](She draws)[] I don't want this. But I'll finish it.",
                               o=[dict(t="Then let's finish it.", go=None, a='NPCHostile#ekg_w_sera_band;SetVariable#ekg_c_warriors_sera,1'),
                                  dict(t="You're a real soldier, Morg says. Why serve Varrek?", go=2)]),
                          dict(t="[BLUE](She hesitates)[] Because the King forgot us after the war. Because the Guild wanted oaths and gave soup. Varrek remembered our names.",
                               o=[dict(t="Varrek is buying monsters to burn villages. Is that the soldier you are?", go=3),
                                  dict(t="Enough talk.", go=None, a='NPCHostile#ekg_w_sera_band;SetVariable#ekg_c_warriors_sera,1')]),
                          dict(t="...Monsters. [BLUE](A long silence; the wind howls over the peak)[] I thought the beast-work was rumour. [BLUE](She sheathes her swords)[] The giants keep the gold; I won't take it back. But the Company will not get them from me. And when you see Varrek, you tell him Sera Blackwell is done.",
                               o=[dict(t='Go well, Captain.', go=None, a='NPCDespawn#ekg_w_sera_band;SetVariable#ekg_c_warriors_sera,2;GainXP#800')]),
                      ]),
                 dict(label='giant', at='NI_warriors_morg', need=['NPCIsDead#D13_giant'],
                      j="With Blackwell dealt with, the giants' new chief still holds Company gold. I must kill the giant chief on Sanctuary Peak and report to Morg in Nivarian.",
                      scene=[
                          dict(t=[('VariableEqual#ekg_c_warriors_sera,2', "Blackwell walked away? [BLUE](Morg laughs, surprised)[] Then you did something I couldn't: you made a Company captain remember what she was. And the chief?"),
                                  (None, "Blackwell's dead. A waste of a good soldier, but she chose her colours. And the chief?")],
                               o=[dict(t='Dead. The Company gets no giants.', go=1)]),
                          dict(t="Good. [BLUE](He presses a heavy purse into your hand)[] From the Nivarian hall. Tell Daukar the warmasters are watching you now; that is both a compliment and a warning.",
                               o=[dict(t="I'll tell her.", go=None, a='GainGold#1500;GainXP#1500')]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 5
        dict(title='Crown and Coin', level=16, rep=7, promote=True,
             brief="Vane has moved. He stood up in the King's council and asked for the Guild's charter to be given to the Company, citing 'the Guild's failures on the roads'. We need proof of what he's done, and we need it before the next council. His letters to Varrek travel by Company courier along [BLUE]the Imperial Coast[]. Take them.",
             steps=[
                 dict(label='courier', at='NG_warriors_daukar', need=['NPCIsDead#ekg_w_maddoc'],
                      j="Lord Vane's letters to Varrek travel by Company courier, Maddoc, along the Imperial Coast. I must take them and bring them to Daukar.",
                      scene=[
                          dict(t=B % "You empty Maddoc's satchel on Daukar's table: a bundle of letters sealed with Vane's crest" + " [BLUE](She reads in silence, then reads again)[] 'Beast-work'. 'The Guild's charter'. 'Your share of the road tolls'. He signed them. The fool signed them.",
                               o=[dict(t='What do we do with them?', go=1, a='GainItem#9502')]),
                          dict(t="That's your decision, not mine. You carried them. We can take them to the Royal Magistrate: Vane falls in public, the council sees the Company for what it is, and every lord who took Vane's coin becomes our enemy. Or we keep them. Quietly. Vane withdraws his petition, the Guild keeps its charter, and he owes us for the rest of his life.",
                               o=[dict(t="The Magistrate. Let everyone see.", go=2, a='SetVariable#ekg_c_warriors_vane,1;LoseItems#9502,1'),
                                  dict(t="We keep them. A leash for a lord.", go=3, a='SetVariable#ekg_c_warriors_vane,2')]),
                          dict(t="Then it's done openly, the way the founders would have wanted. [BLUE](She seals the letters with the guild's seal)[] It'll cost us friends. But Varrek loses his lord, and a Company without a paymaster is just a mob. You have the heart of a Champion. From today you have the rank as well.",
                               o=[dict(t="I'll wear it well.", go=None)]),
                          dict(t="[BLUE](She smiles thinly)[] Varrek would have done the same. Maybe that's why it's the right choice, and maybe that's why I hate it. Keep them somewhere safe. Vane will try to buy them back, and when he can't, he'll try to kill you. You are a Champion of the Warriors' Guild now. Act like one.",
                               o=[dict(t="I'll wear it well.", go=None)]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 6
        dict(title='Horns of the Underking', level=18, rep=10, promote=True,
             brief="Varrek has answered. The minotaurs of the Ashen Wastes marched on our Nivarian outposts last week, with red-sashed men behind them. He found another Binder, or bought one. [BLUE]Morg[] is gathering a warband in Nivarian. Go and lead it.",
             steps=[
                 dict(label='morg', at='NI_warriors_morg',
                      j="Varrek has turned the minotaurs of the Ashen Wastes on our Nivarian outposts. Morg is gathering a warband in Nivarian.",
                      scene=[
                          dict(t="Three outposts burned. Nine of ours dead. [BLUE](Morg's voice is flat)[] The herd comes from the [BLUE]Sunken Citadel[], and the [BLUE]Underking[] leads it, with one of Varrek's beastbinders at his side, whispering in his ear.",
                               o=[dict(t='Is it Oreth? I let him go.', go=1, c='VariableEqual#ekg_c_warriors_oreth,1'),
                                  dict(t="What's the plan?", go=2)]),
                          dict(t="No. Oreth was seen begging in Freetown, drunk and half blind; the Company took his stone. This one is new, and worse. Mercy is still a soldier's right, but Varrek always has another knife.",
                               o=[dict(t="What's the plan?", go=2)]),
                          dict(t="My warband holds the passes. You go in: kill the binder first, then the Underking. Without the binder the herd scatters; without the Underking it never gathers again. Then come back to me.",
                               o=[dict(t="Consider it done.", go=None)]),
                      ]),
                 dict(label='citadel', at='NI_warriors_morg', need=['NPCIsDead#ekg_w_handler', 'NPCIsDead#mino_underking'],
                      j="I must kill the Crimson Beastbinder and the Minotaur Underking in the Sunken Citadel, in the Ashen Wastes, then report to Morg.",
                      scene=[
                          dict(t="The herd broke and ran into the wastes, and my people held the passes. Not one more outpost burned. [BLUE](Morg grips your forearm, warrior to warrior)[] The warmasters have spoken. You are one of us now.",
                               o=[dict(t="It's an honour, Warmaster.", go=None)]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 7
        dict(title='The Crimson Company', level=20, rep=12,
             brief="It ends now. Varrek has pulled what's left of the Company into [BLUE]the Imperial Fortress[] on the Steel Coast, and he has sent me a challenge in his own hand: the Guild's best, alone, at the gate. Before you go, talk to [BLUE]Brann[]. He has something to say, and he's been working up to it for a week.",
             steps=[
                 dict(label='brann', at='ekg_w_brann',
                      j="Varrek Dunmore has challenged the Guild's best to meet him at the Imperial Fortress. Daukar asked me to speak with Brann first.",
                      scene=[
                          dict(t="So she told you. [BLUE](Brann sets down the whetstone)[] I served under Varrek for eleven years. He taught me to read a road, and to pull an arrow, and to stand in a line when every part of you wants to run.",
                               o=[dict(t='What happened to him?', go=1)]),
                          dict(t="The war. The King cut our pay to half and the Guild told us honour would feed our families. Varrek's wife died that winter. He came back from the funeral, took off his oath-ring, and put it on Daukar's table. I stayed. I've wondered every day since which of us was the fool.",
                               o=[dict(t="He's burned villages since. He isn't that man anymore.", go=2),
                                  dict(t='What do you want me to do?', go=2)]),
                          dict(t="I know. I know. [BLUE](He looks at his hands)[] Just... if there's a way to end it without a grave, look for it. And if there isn't, make it quick. He'd do the same for me.",
                               o=[dict(t="I'll look for a way.", go=None)]),
                      ]),
                 dict(label='varrek', at='ekg_w_varrek',
                      j="Varrek Dunmore waits for me inside the Imperial Fortress, on the Steel Coast.",
                      scene=[
                          dict(t=[('VariableEqual#ekg_c_warriors_sera,2', B % "A tall man in black plate waits in the ruined hall, a greatsword across his knees. Two lieutenants flank him; there is an empty place where a third should stand" + " Sera sends her regards, I suppose. Blackwell always did have a conscience. So you're the one the Guild sends."),
                                  (None, B % "A tall man in black plate waits in the ruined hall, a greatsword across his knees, two lieutenants at his side" + " So you're the one the Guild sends.")],
                               o=[dict(t='Varrek Dunmore. It ends today.', go=1),
                                  dict(t='Brann asked me to find another way.', go=2)]),
                          dict(t="Everything ends. The Guild ended the day it told starving men to eat their oaths. I just stopped pretending. The beasts, the farms... [BLUE](He shrugs, but his eyes do not move from you)[] You don't win a war with clean hands. The King taught me that. So did your Sergeant.",
                               o=[dict(t='Brann asked me to find another way.', go=2),
                                  dict(t='Enough. Draw your sword.', go=None, a='NPCHostile#ekg_w_company;SetVariable#ekg_c_warriors_varrek,1')]),
                          dict(t="[BLUE](For the first time, something cracks in his face)[] Brann. Still alive, the old goat. [BLUE](A long breath)[] What other way? A cell in New Garand while Vane's friends sharpen the axe?",
                               o=[dict(t="Vane has fallen. The Magistrate has his letters. Testify against him and you'll hang no one but the guilty.", go=3, c='VariableEqual#ekg_c_warriors_vane,1'),
                                  dict(t="I hold Vane's letters. Surrender, and the Guild will see you judged fairly.", go=4, c='VariableEqual#ekg_c_warriors_vane,2'),
                                  dict(t="There's no other way. Draw your sword.", go=None, a='NPCHostile#ekg_w_company;SetVariable#ekg_c_warriors_varrek,1')]),
                          dict(t="[BLUE](Varrek laughs, and it turns into something else)[] Vane, in chains. Then the Company is paying for a war it already lost. [BLUE](He lays the greatsword on the floor)[] Tell Brann... tell him I'll see him at the trial. [BLUE](His lieutenants lower their weapons and follow him out)[]",
                               o=[dict(t="Brann will be there.", go=None, a='NPCDespawn#ekg_w_company;SetVariable#ekg_c_warriors_varrek,2;GainXP#2500')]),
                          dict(t="Fairly. [BLUE](A cold smile)[] You hold a council lord by the throat and you want to talk to me about fair. No. You're more like me than Brann ever was. [BLUE](He stands, and the lieutenants draw)[] So let's settle this the old way.",
                               o=[dict(t='So be it.', go=None, a='NPCHostile#ekg_w_company;SetVariable#ekg_c_warriors_varrek,1')]),
                      ]),
                 dict(label='report', at='NG_warriors_daukar',
                      need=[],
                      alt_need=[['VariableEqual#ekg_c_warriors_varrek,2'], ['NPCIsDead#ekg_w_varrek']],
                      j="The confrontation at the Imperial Fortress is over. I must report to Daukar.",
                      scene=[
                          dict(t=[('VariableEqual#ekg_c_warriors_varrek,2', "He surrendered? To you? [BLUE](Daukar sits down, slowly)[] Twenty years I waited to see that man in chains, and now I don't know what I feel. Brann went to the gaol an hour ago. He's still there."),
                                  (None, "It's over, then. [BLUE](She is quiet for a long time)[] He was the best sergeant this guild ever had, once. Brann won't talk about it. Give him time.")],
                               o=[dict(t='The Crimson Company is finished.', go=1)]),
                          dict(t="And the Guild is still standing. Because of you. [BLUE](She looks at the founders' wall, at the scratched-out name that was Varrek's)[] There is one thing left. Come back when you're ready for it. It's the last thing I will ever ask of you.",
                               o=[dict(t="I'll be ready.", go=None, a='GainXP#3000;GainGold#3000')]),
                      ]),
             ]),
        # ------------------------------------------------------------------ 8
        dict(title="The Founders' Oath", level=21, rep=14, promote=True, master=True,
             brief="I'm old, and the Guild needs someone to lead it who can still swing a sword. The founders wrote a law, before the kingdoms had names: whoever slays an elder dragon may claim the seat. Nobody has managed it in a hundred years. First you'll need the blessing of the other halls: [BLUE]Toel[] in Freetown and [BLUE]Morg[] in Nivarian. Then [BLUE]Basrudaxul[], in the Bappasalar Cave. Understand this: a Guild Master serves one guild alone. Every other oath you have sworn will be released.",
             steps=[
                 dict(label='toel', at='FT_warriors_toel',
                      j="To claim the Guild Master's seat I need the blessing of Toel in Freetown and of Morg in Nivarian, then I must slay the elder dragon Basrudaxul.",
                      scene=[
                          dict(t="So Daukar is finally stepping down, and she's chosen you. [BLUE](Toel smiles)[] Freetown's hall gives its blessing. And Freetown's hall wants to be there when you do it; bring me a tooth.",
                               o=[dict(t="A tooth. I'll see what I can do.", go=None, a='GainXP#1000')]),
                      ]),
                 dict(label='morg', at='NI_warriors_morg',
                      j="Toel has given Freetown's blessing. Next, Morg in Nivarian.",
                      scene=[
                          dict(t="[BLUE](Morg does not smile, but he bows, which is rarer)[] Nivarian gives its blessing. The founders' law is a hard law. Most who tried it are still in that cave. Don't join them.",
                               o=[dict(t="I don't intend to.", go=None, a='GainXP#1000')]),
                      ]),
                 dict(label='dragon', at='NG_warriors_daukar', need=['NPCIsDead#H4_dragon_elder'],
                      j="Both halls have given their blessing. I must slay Basrudaxul, the elder red dragon of the Bappasalar Cave in the Southern Dragon Mountains, and return to Daukar.",
                      scene=[
                          dict(t=B % "The whole hall is gathered. Toel came from Freetown, Morg from Nivarian. Brann stands at the front, leaning on a cane and grinning" + " Basrudaxul is dead. [BLUE](Daukar's voice carries to the rafters)[] By the founders' law, spoken before the kingdoms had names...",
                               o=[dict(t=B % "Kneel", go=1)]),
                          dict(t=[('VariableEqual#ekg_c_warriors_lyse,1', "...I stand aside. [BLUE](Somewhere behind you, Lyse Corwen is writing it all down in a ledger, and pretending not to cry)[] Rise, Guild Master of the Warriors' Guild."),
                                  (None, "...I stand aside. Rise, Guild Master of the Warriors' Guild.")],
                               o=[dict(t=B % "Rise", go=2)]),
                          dict(t="The seat is yours, and the charter, and every recruit's fool question at dawn. [BLUE](Daukar grins)[] I'm going to sleep for a month. Brann says he's staying on as your second, and I pity you both.",
                               o=[dict(t="Thank you, Daukar. For everything.", go=None)]),
                      ]),
             ]),
    ])

STORIES = {'warriors': WARRIORS}
