package net.fdgames.GameEntities.CharacterSheet;

/* JADX INFO: loaded from: /tmp/tmp.I6QUuWp8g5/classes.dex */
public class CharacterEffects {
    public Boolean bloodlust;
    public int bloodlustArmorBonus;
    public int bloodlustBonus;
    public Boolean disintegrate;
    public int disintegrateBonus;
    public Boolean duel;
    public int duelbonus;
    public Boolean evasion;
    public Boolean fatigued;
    public boolean flameAura;
    public boolean flurry;
    public Boolean fury;
    public int furyBonus;
    public float furyMultiplier;
    public int holy_shieldBonus;
    public Boolean holy_shielded;
    public int mageArmorBonus;
    public int mageArmorElementalBonus;
    public int mageArmor_Charges;
    public Boolean might;
    public int mightBonus;
    public int mightBonus_arbenos;
    public int mightBonus_prayer;
    public Boolean might_arbenos;
    public Boolean might_prayer;
    public Boolean poison;
    public int poisonBonus;
    public Boolean rage;
    public int rageArmorBonus;
    public int rageStrBonus;
    public boolean rapid_fire;
    public CharacterResistances resistances;
    public Boolean rooted;
    public int shieldBonus;
    public Boolean shielded;
    public Boolean slowed;
    public Boolean speed;
    public Boolean stab;
    public int stabBonus;
    public Boolean stealth;
    public Boolean stunned;

    public CharacterEffects() {
        Boolean bool = Boolean.FALSE;
        this.rooted = bool;
        this.slowed = bool;
        this.speed = bool;
        this.stunned = bool;
        this.evasion = bool;
        this.rapid_fire = false;
        this.flurry = false;
        this.shielded = bool;
        this.shieldBonus = 0;
        this.holy_shielded = bool;
        this.holy_shieldBonus = 0;
        this.stealth = bool;
        this.fury = bool;
        this.furyBonus = 0;
        this.furyMultiplier = 0.0f;
        this.rage = bool;
        this.rageStrBonus = 0;
        this.rageArmorBonus = 0;
        this.fatigued = bool;
        this.stab = bool;
        this.stabBonus = 0;
        this.disintegrate = bool;
        this.disintegrateBonus = 0;
        this.might = bool;
        this.mightBonus = 0;
        this.might_arbenos = bool;
        this.mightBonus_arbenos = 0;
        this.might_prayer = bool;
        this.mightBonus_prayer = 0;
        this.bloodlust = bool;
        this.bloodlustBonus = 0;
        this.bloodlustArmorBonus = 0;
        this.mageArmor_Charges = 0;
        this.mageArmorBonus = 0;
        this.mageArmorElementalBonus = 0;
        this.resistances = new CharacterResistances();
        this.flameAura = false;
        this.poison = bool;
        this.poisonBonus = 0;
        this.duel = bool;
        this.duelbonus = 0;
    }
}
